"""Source copy for 15 distinct, patient-facing workplace eye articles.

Each tuple: title, slug, summary, situation, practical steps, seek care,
question, answer, primary source URL, relevant internal URL.
These are informational articles, not a clinician's individualized advice.
"""

ARTICLES = [
    (
        "Màn hình bị lóa khi làm việc: chỉnh ánh sáng trước khi mua kính",
        "man-hinh-bi-loa-khi-lam-viec",
        "Lóa trên màn hình khiến chữ khó đọc và người làm việc dễ nheo mắt, nghiêng đầu hoặc tăng độ sáng quá mức. Trước khi quy vấn đề cho mắt yếu, hãy quan sát hướng cửa sổ, đèn trần và mặt bàn.",
        "Ánh sáng phản chiếu từ cửa kính hoặc đèn phía sau người ngồi có thể hiện thành mảng sáng trên màn hình. Độ tương phản lớn giữa màn hình và phòng cũng khiến việc chuyển nhìn liên tục kém dễ chịu. Đây là vấn đề bố trí nơi làm việc; một cặp kính mới không tự loại bỏ nguồn lóa. Nếu chỉ một vị trí ngồi gây khó chịu, hãy thử đổi hướng màn hình trước khi đánh giá thị lực.",
        "Đặt màn hình gần vuông góc với cửa sổ, điều chỉnh rèm và chuyển đèn bàn để ánh sáng không chiếu thẳng vào mặt kính. Lau màn hình và dùng mức sáng vừa với ánh sáng xung quanh. Nếu phải nheo mắt để đọc chữ nhỏ, tăng cỡ chữ thay vì cúi sát. Sau mỗi khoảng làm việc tập trung, nhìn ra xa và chớp mắt tự nhiên; việc nghỉ mắt không thay thế cho chỉnh ánh sáng.",
        "Nếu vẫn nhìn mờ, đau đầu tái diễn, nhìn đôi hoặc một mắt nhìn kém hơn mắt kia dù đã đổi vị trí và cỡ chữ, nên khám mắt để kiểm tra khúc xạ và nguyên nhân khác. Đau mắt rõ, đỏ nhiều hoặc giảm thị lực mới xuất hiện cần được đánh giá sớm, không chỉ thay màn hình hay mua kính chống ánh sáng xanh.",
        "Dán kính chống lóa có giải quyết mọi trường hợp?",
        "Không. Miếng lọc chỉ có thể giảm một số phản xạ; hướng nguồn sáng, độ sạch màn hình và cỡ chữ vẫn cần được điều chỉnh.",
        "https://www.osha.gov/etools/computer-workstations/workstation-environment",
        "/kien-thuc/quy-tac-20-20-20-cho-nguoi-lam-may-tinh/",
    ),
    (
        "Màn hình đặt quá gần hay quá cao: cách kiểm tra góc nhìn khi làm việc",
        "vi-tri-man-hinh-va-goc-nhin",
        "Khoảng cách và độ cao màn hình ảnh hưởng cả tư thế cổ lẫn mức dễ chịu của mắt. Không có một con số phù hợp tuyệt đối cho mọi kích thước màn hình; điểm quan trọng là đọc rõ mà không phải rướn cổ hoặc cúi sát.",
        "Nếu màn hình đặt cao hơn tầm mắt, người dùng có thể ngửa đầu hoặc mở mắt rộng hơn trong thời gian dài. Đặt quá gần trong khi chữ vẫn nhỏ cũng dễ dẫn tới nheo mắt. Nhiều người đổi kính liên tục nhưng chưa từng thử thay vị trí màn hình; vì vậy cần tách vấn đề nơi làm việc khỏi vấn đề độ kính.",
        "Đặt màn hình thẳng trước mặt, cách mắt ít nhất khoảng 50 cm theo gợi ý của OSHA, rồi điều chỉnh theo khả năng đọc thực tế. Mép trên màn hình nên ngang hoặc thấp hơn tầm mắt; tăng kích thước chữ và độ tương phản để giữ tư thế thoải mái. Với hai màn hình, đặt màn hình dùng thường xuyên hơn ở vị trí chính diện. Xen kẽ việc đọc giấy, họp hoặc nhìn xa để mắt không phải nhìn gần liên tục.",
        "Nếu phải dí sát dù đã phóng chữ, hoặc có nhìn mờ khi rời màn hình, nên kiểm tra thị lực và kính đang dùng. Người trên 40 tuổi có thể cần đánh giá nhu cầu kính nhìn gần hoặc khoảng cách trung gian; không tự chọn độ kính chỉ theo khoảng cách màn hình đo được.",
        "Đặt màn hình thấp có làm hỏng mắt không?",
        "Không nên diễn giải thành tổn thương mắt chắc chắn. Vị trí không hợp lý thường gây khó chịu và tư thế xấu; cần chỉnh theo cơ thể và công việc.",
        "https://www.osha.gov/etools/computer-workstations/components/monitors",
        "/kien-thuc/kinh-khong-con-dung-do-khi-nao-do-lai/",
    ),
    (
        "Ngồi phòng điều hòa bị khô mắt: kiểm tra luồng gió và thói quen nhìn màn hình",
        "kho-mat-trong-phong-dieu-hoa",
        "Rát, cộm hoặc chảy nước mắt khi làm việc trong phòng điều hòa không nhất thiết là dị ứng. Luồng gió trực tiếp, không khí khô và thời gian nhìn màn hình kéo dài có thể cùng làm triệu chứng rõ hơn.",
        "Khô mắt có nhiều nguyên nhân, từ lớp nước mắt không ổn định đến tình trạng mi hoặc thuốc đang dùng. Khi tập trung nhìn gần, người làm việc thường chớp mắt ít hơn; nếu gió lạnh thổi trực tiếp vào mặt, cảm giác khô có thể tăng. Chỉ dựa vào địa điểm xuất hiện triệu chứng chưa đủ để tự xác định bệnh hay chọn loại thuốc nhỏ.",
        "Thử đổi chỗ ngồi hoặc hướng miệng gió, nghỉ nhìn gần đều đặn và chủ động chớp mắt đầy đủ. Tránh để quạt hoặc điều hòa thổi thẳng vào mặt. Nếu đang đeo kính áp tròng và mắt cộm, trao đổi với người khám về thời gian đeo và cách vệ sinh. Không lạm dụng thuốc nhỏ làm trắng mắt hoặc thuốc có thành phần điều trị khi chưa biết nguyên nhân.",
        "Khám mắt nếu triệu chứng kéo dài, tái phát dù đã chỉnh môi trường, hoặc cần nhỏ nước mắt nhân tạo liên tục mà không rõ lý do. Đau, sợ ánh sáng, đỏ nhiều, nhìn mờ rõ hoặc chỉ một mắt bị nặng hơn cần được kiểm tra sớm để loại trừ vấn đề bề mặt giác mạc.",
        "Ra khỏi phòng điều hòa thấy đỡ thì có cần khám không?",
        "Nếu hiện tượng thường xuyên quay lại, ảnh hưởng công việc hoặc kèm mờ/đau, vẫn nên khám để xác định nguyên nhân thay vì chỉ đổi chỗ ngồi.",
        "https://www.nei.nih.gov/eye-health-information/eye-conditions-and-diseases/dry-eye",
        "/kien-thuc/kho-mat-nguyen-nhan-va-xu-tri/",
    ),
    (
        "Làm ca đêm và mỏi mắt: phân biệt mệt do lịch làm với dấu hiệu cần khám",
        "lam-ca-dem-va-moi-mat",
        "Mắt mỏi ở cuối ca đêm có thể đi cùng thời gian nhìn gần, ánh sáng không hợp lý hoặc thiếu ngủ. Tuy nhiên, không nên gán mọi lần nhìn mờ, đau mắt cho việc làm ca.",
        "Ca đêm thường buộc người lao động chuyển liên tục giữa màn hình sáng, khu vực tối và đường về nhà. Sự thay đổi này làm triệu chứng khô hoặc lóa dễ được nhận thấy hơn. Lịch làm kéo dài cũng có thể khiến người lao động bỏ qua giờ nghỉ và trì hoãn khám. Bản thân cảm giác mỏi không cho biết có tật khúc xạ, khô mắt hay bệnh lý khác.",
        "Bố trí đèn đủ sáng nhưng không chiếu thẳng vào màn hình; tăng cỡ chữ và nghỉ nhìn gần trong ca. Trước khi lái xe về, tự đánh giá xem mình có nhìn rõ biển báo, đèn xe và đường đi không. Nếu buồn ngủ hoặc thị lực không đảm bảo, cần chọn cách di chuyển an toàn khác. Không tự mua kính có độ chỉ vì mờ vào cuối ca.",
        "Nếu nhìn mờ lặp lại kể cả khi đã ngủ đủ, nhìn một mắt kém hơn, thấy quầng sáng mới xuất hiện, hoặc đau đỏ, hãy khám mắt. Giảm thị lực đột ngột, nhìn đôi hoặc đau dữ dội không nên chờ đến hết lịch ca. Khi đi khám, mang kính đang dùng và ghi lại thời điểm triệu chứng xuất hiện.",
        "Mỏi mắt sau ca đêm có đồng nghĩa phải đổi kính?",
        "Không. Cần đo thị lực và đánh giá triệu chứng trong bối cảnh giấc ngủ, ánh sáng, bề mặt mắt và kính hiện tại.",
        "https://www.osha.gov/etools/computer-workstations/workstation-environment",
        "/kien-thuc/lai-xe-ban-dem-nhin-kem/",
    ),
    (
        "Đeo kính áp tròng khi làm ở nơi nhiều bụi: điều gì cần cân nhắc?",
        "kinh-ap-trong-khi-lam-viec-nhieu-bui",
        "Kính áp tròng không phải kính bảo hộ. Người làm ở nơi có bụi hoặc nguy cơ bắn vật nhỏ cần đánh giá loại bảo vệ mắt theo công việc, dù có đeo kính áp tròng hay không.",
        "Bụi có thể gây cộm và khiến người đeo kính áp tròng muốn dụi mắt hoặc tháo kính bằng tay chưa sạch. Trong môi trường hóa chất, không có cơ sở để cấm tuyệt đối mọi người đeo kính áp tròng, nhưng NIOSH yêu cầu đánh giá nguy cơ và dùng bảo hộ phù hợp. Quy định của nơi làm việc và tư vấn cá nhân từ bác sĩ cần được ưu tiên.",
        "Hỏi bộ phận an toàn lao động loại kính bảo hộ dành cho bụi, mảnh bắn hoặc hóa chất tại vị trí của mình. Rửa và lau khô tay trước khi chạm kính áp tròng; chuẩn bị hộp đựng, dung dịch chăm sóc đúng loại và kính gọng dự phòng. Không dùng nước máy để ngâm hoặc rửa kính áp tròng. Nếu mắt cộm, ngừng công việc nguy cơ rồi xử lý trong điều kiện sạch.",
        "Đỏ một mắt, đau, sợ sáng, chảy nước mắt nhiều hoặc mờ sau khi đeo kính áp tròng cần khám sớm vì có thể liên quan đến giác mạc. Nếu hóa chất bắn vào mắt, bắt đầu rửa bằng nước ngay và tìm hỗ trợ y tế; không trì hoãn việc rửa để tìm hộp kính.",
        "Kính áp tròng có thay kính bảo hộ được không?",
        "Không. Kính áp tròng chỉnh thị lực; kính bảo hộ được chọn theo nguy cơ va đập, bụi hoặc chất lỏng bắn vào mắt.",
        "https://cdc.gov/niosh/publications/numbered/2005-139.html",
        "/kien-thuc/cach-deo-lens-va-thao-lens-don-gian-cho-nguoi-moi-bat-dau/",
    ),
    (
        "Kính cận thông thường có thay kính bảo hộ ở xưởng được không?",
        "kinh-can-co-thay-kinh-bao-ho-duoc-khong",
        "Một cặp kính có độ giúp nhìn rõ, nhưng thông thường không được thiết kế để chịu va đập hay ngăn mảnh bắn từ bên cạnh. Bảo vệ mắt cần phù hợp với mối nguy tại nơi làm việc.",
        "Khi cắt, mài, khoan hoặc thao tác với chất lỏng, vật nhỏ có thể đi vào mắt theo nhiều hướng. Tròng kính cận thông thường, gọng mảnh và khoảng hở hai bên không chứng minh khả năng bảo vệ. Ngược lại, kính bảo hộ không có độ phù hợp cũng có thể khiến người lao động khó nhìn và thao tác sai. Hai nhu cầu nhìn rõ và bảo vệ cần được giải quyết cùng nhau.",
        "Trao đổi với bộ phận an toàn về kính bảo hộ có độ được chứng nhận cho nguy cơ cụ thể, hoặc loại kính bảo hộ đeo vừa bên ngoài kính cận mà không làm lệch kính bên trong. Thử độ ôm, tầm nhìn và sự thoải mái trước khi dùng cả ca. Nếu công việc có mảnh bắn từ bên, cần bảo vệ phía bên; nếu có chất lỏng bắn, phải chọn loại phù hợp chất lỏng, không chỉ dựa vào hình dáng đẹp.",
        "Sau va chạm vào kính hoặc khi kính nứt, trầy nhiều, không tiếp tục coi đó là lớp bảo vệ đạt yêu cầu. Nếu có vật bắn vào mắt dù đã đeo kính, đau, cộm, sợ sáng hoặc mờ, hãy ngừng việc và khám; không cố tự lấy dị vật ghim trong mắt.",
        "Đeo hai lớp kính có luôn an toàn hơn không?",
        "Chỉ khi loại bảo hộ ngoài vừa vặn, giữ kính có độ đúng vị trí và phù hợp nguy cơ. Cần thử theo quy trình an toàn của nơi làm việc.",
        "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.102",
        "/kien-thuc/deo-kinh-bao-ho-dung-cach/",
    ),
    (
        "Mài và khoan kim loại: vì sao mắt vẫn có thể bị mảnh bắn từ bên?",
        "mai-khoan-kim-loai-bao-ve-mat",
        "Mảnh bắn khi mài hoặc khoan không chỉ đi thẳng phía trước. Khoảng hở quanh kính và việc tháo kính để quan sát nhanh đều làm tăng nguy cơ chấn thương mắt.",
        "Một mảnh rất nhỏ có thể gây đau, chảy nước mắt hoặc để lại tổn thương bề mặt. Có khi cảm giác cộm xuất hiện sau ca, khiến người lao động nghĩ chỉ do bụi. Kính râm, kính cận hoặc kính bảo hộ không ôm sát có thể không phù hợp với luồng mảnh bắn của công việc. Chắn máy, quy trình thao tác và kính bảo hộ cần đi cùng nhau.",
        "Trước khi làm việc, kiểm tra tấm chắn máy và loại kính được bộ phận an toàn chỉ định; chú ý phần bảo vệ hai bên và tình trạng tròng kính. Không tháo kính khi máy còn chạy hoặc khi đồng nghiệp ở gần đang mài. Khi phải quan sát chi tiết, dừng công đoạn nguy cơ rồi mới điều chỉnh kính. Vệ sinh kính để vết xước hoặc bụi bám không làm giảm tầm nhìn.",
        "Nếu thấy vật ghim vào mắt, không dụi, ấn hoặc cố lấy bằng tay. Che bảo vệ mắt nhẹ nhàng và đến cơ sở cấp cứu/nhãn khoa. Đau nhiều, sợ sáng, nhìn mờ hoặc cảm giác cộm không hết sau khi rời khu vực cũng cần được khám, kể cả mắt không đỏ nhiều.",
        "Mảnh nhỏ không thấy bằng mắt thường có thể bỏ qua?",
        "Không nên. Triệu chứng và hoàn cảnh bị bắn quan trọng hơn kích thước người lao động tự quan sát được.",
        "https://www.cdc.gov/niosh/ppe/eye-safety/index.html",
        "/kien-thuc/di-vat-bay-vao-mat-xu-ly-the-nao/",
    ),
    (
        "Nước tẩy rửa bắn vào mắt khi làm vệ sinh: xử lý phút đầu",
        "nuoc-tay-rua-ban-vao-mat-khi-lam-viec",
        "Khi chất tẩy rửa bắn vào mắt, việc đầu tiên là bắt đầu rửa bằng nước sạch đang chảy. Không chờ tìm thuốc nhỏ, không cố trung hòa bằng một hóa chất khác.",
        "Các sản phẩm vệ sinh khác nhau về thành phần và nồng độ, nên mức tổn thương không thể đoán chỉ từ nhãn 'nước tẩy'. Đau, đỏ hoặc nhìn mờ có thể xuất hiện ngay nhưng cũng không phản ánh hết mức ảnh hưởng. Bao bì hoặc nhãn sản phẩm sẽ giúp nhân viên y tế biết chất đã tiếp xúc; hãy giữ lại nếu có thể làm an toàn.",
        "Rời nguồn hóa chất, giữ hai mí mắt mở và rửa liên tục bằng nhiều nước sạch, nhẹ nhàng, tối thiểu 15 phút theo hướng dẫn sơ cứu của NIOSH; tháo kính áp tròng nếu lấy ra dễ dàng trong lúc tiếp tục rửa. Nhờ người khác gọi hỗ trợ, nhưng không dừng rửa chỉ để gọi điện. Sau rửa, đến cơ sở y tế để được đánh giá; không dùng thuốc nhỏ hoặc băng ép theo suy đoán.",
        "Nếu đau nhiều, không mở được mắt, thị lực giảm, bề mặt mắt trắng đục hoặc hóa chất đậm đặc, cần cấp cứu ngay sau khi bắt đầu rửa. Với mọi chất chưa rõ mức nguy hiểm, nên liên hệ cơ sở y tế và cung cấp tên sản phẩm; đừng quay lại làm việc chỉ vì cảm giác rát giảm tạm thời.",
        "Có nên dùng nước muối sinh lý thay nước máy?",
        "Dùng nước sạch có ngay để bắt đầu rửa; không trì hoãn để đi tìm dung dịch khác. Nhân viên y tế sẽ hướng dẫn bước tiếp theo.",
        "https://www.cdc.gov/niosh/npg/firstaid.html",
        "/kien-thuc/mat-bi-cham-thuong-do-vat-nhon/",
    ),
    (
        "Bụi xi măng vào mắt ở công trường: vì sao không nên chỉ dụi cho hết cộm?",
        "bui-xi-mang-vao-mat-cong-truong",
        "Bụi xi măng vừa là hạt gây cộm vừa có tính kiềm khi gặp nước. Vì vậy, mắt tiếp xúc không nên được xử lý như một hạt bụi vô hại.",
        "Dụi mắt có thể làm hạt cọ xát bề mặt giác mạc. Xi măng ướt hoặc hỗn hợp vữa bắn vào mắt còn gây nguy cơ kích ứng hóa học. Mức độ không thể tự đánh giá qua việc nhìn thấy bao nhiêu bột ở mí mắt. Người làm công trường cần biết vị trí nguồn nước rửa mắt trước ca, thay vì đợi có tai nạn mới tìm.",
        "Ngừng công việc và rửa mắt ngay bằng nhiều nước sạch, giữ mí mở để nước cuốn trôi hạt. Không tự dùng ngón tay, tăm bông hoặc nhíp lấy hạt bám sâu. Sau đó mang thông tin vật liệu đến cơ sở y tế; nếu tiếp xúc với vữa hoặc xi măng ướt, cần đánh giá sớm. Phòng ngừa bằng kính bảo hộ phù hợp với bụi bắn, che chắn công đoạn và vệ sinh tay trước khi chạm mắt.",
        "Đau kéo dài, mắt đỏ, sợ sáng hoặc nhìn mờ sau rửa là lý do khám ngay trong ngày. Nếu có nhiều vật liệu bắn vào mắt, đừng đợi đến khi hết ca. Bác sĩ sẽ kiểm tra xem còn hạt trong cùng đồ hay tổn thương bề mặt mắt hay không.",
        "Rửa xong thấy đỡ thì có cần báo sự cố?",
        "Nên báo theo quy trình an toàn của nơi làm việc và theo dõi triệu chứng; đau hoặc nhìn mờ cần được kiểm tra y tế.",
        "https://www.cdc.gov/niosh/npg/npgd0521.html",
        "/kien-thuc/bui-va-hoa-chat-trong-moi-truong-lam-viec/",
    ),
    (
        "Phun thuốc bảo vệ thực vật: bảo vệ mắt và xử trí khi bị bắn",
        "phun-thuoc-bao-ve-thuc-vat-bao-ve-mat",
        "Thuốc bảo vệ thực vật có nhiều hoạt chất, nồng độ và hướng dẫn sơ cứu khác nhau. Người pha hoặc phun cần đọc nhãn sản phẩm và chuẩn bị phương tiện bảo vệ mắt đúng loại trước khi mở nắp.",
        "Giọt thuốc có thể bắn khi pha, thay vòi, tháo bình hoặc gặp gió đổi hướng. Kính cận và kính râm không thay cho bảo hộ chống bắn. Nếu mắt tiếp xúc, không thể quyết định mức độ nguy hiểm chỉ từ lượng thuốc nhìn thấy; một số sản phẩm cần xử trí rất sớm.",
        "Đọc nhãn để chọn kính, găng và các phương tiện bảo hộ được yêu cầu; kiểm tra kính ôm vừa và không mờ trước khi làm. Chuẩn bị sẵn nước rửa mắt ở nơi dễ tiếp cận. Khi thuốc bắn vào mắt, giữ mí mở và rửa ngay bằng dòng nước sạch nhẹ ít nhất 15 phút theo hướng dẫn chung của EPA; làm theo nhãn nếu nhãn yêu cầu thêm bước cụ thể. Không pha hóa chất khác vào nước rửa.",
        "Sau khi rửa, liên hệ cơ sở y tế và mang nhãn hoặc hình chụp rõ tên sản phẩm. Đau, đỏ, nhìn mờ, khó thở hoặc triệu chứng toàn thân cần được cấp cứu; không tự lái xe nếu nhìn kém. Người đi cùng nên thông báo thời điểm tiếp xúc, cách sơ cứu và loại sản phẩm cho nhân viên y tế.",
        "Chỉ một giọt bắn vào mắt có cần xử trí không?",
        "Có. Bắt đầu rửa ngay, xem nhãn sản phẩm và hỏi nhân viên y tế; đừng chờ đau nhiều mới sơ cứu.",
        "https://www.epa.gov/pesticide-incidents/first-aid-case-pesticide-exposure",
        "/kien-thuc/mat-bi-cham-thuong-do-vat-nhon/",
    ),
    (
        "Làm việc ngoài trời: chọn kính chống tia UV cho mắt",
        "lam-viec-ngoai-troi-bao-ve-mat-tia-uv",
        "Người giao hàng, xây dựng, nông nghiệp hoặc thường xuyên làm việc ngoài trời cần bảo vệ mắt khỏi tia cực tím. Màu kính tối không chứng minh khả năng lọc UV.",
        "Tia UV có thể tác động đến mắt và vùng da quanh mắt; mặt nước, cát và bề mặt sáng còn phản xạ ánh nắng. Một cặp kính râm chỉ đẹp hoặc tối màu nhưng không ghi mức bảo vệ rõ ràng có thể gây hiểu lầm. Kính dùng để chống nắng cũng không mặc nhiên là kính chống va đập trong công trường.",
        "Chọn kính ghi rõ chặn 99–100% UVA và UVB hoặc UV400, ôm vừa và che được ánh sáng từ hai bên; đội thêm mũ vành phù hợp. Nếu công việc có nguy cơ mảnh bắn, cần loại bảo hộ đáp ứng cả nguy cơ cơ học theo đánh giá an toàn lao động. Giữ kính sạch để vẫn nhìn rõ đường đi và thiết bị. Người đeo kính áp tròng vẫn cần kính chống UV che vùng mắt bên ngoài kính.",
        "Nếu đau mắt sau phơi sáng mạnh, sợ sáng, nhìn mờ hoặc đỏ kéo dài, hãy khám để xác định nguyên nhân. Không nhìn trực tiếp mặt trời hoặc nguồn sáng hàn; kính chống nắng thông thường không dùng thay mặt nạ hàn chuyên dụng.",
        "Kính càng đen càng chống UV tốt?",
        "Không. Hãy kiểm tra thông tin lọc UVA/UVB hoặc UV400 trên sản phẩm, không đánh giá bằng độ tối của tròng.",
        "https://www.nei.nih.gov/research-and-training/research-news/protecting-your-eyes-suns-uv-light",
        "/kien-thuc/he-dung-cham-da-ma-quen-mat-bac-si-tiet-lo-ly-do/",
    ),
    (
        "Nhân viên y tế: kính bảo vệ mắt trước nguy cơ giọt bắn",
        "nhan-vien-y-te-kinh-bao-ve-mat-giot-ban",
        "Trong chăm sóc người bệnh, mắt có thể tiếp xúc với giọt bắn, dịch cơ thể hoặc hóa chất khử khuẩn. Loại bảo vệ được chọn theo thao tác và đánh giá nguy cơ, không chỉ theo việc có đeo kính cận hay không.",
        "Kính cận thông thường để hở hai bên nên không bảo vệ trước giọt bắn như kính bảo hộ kín phù hợp. Tấm chắn mặt che vùng mặt rộng hơn nhưng cách dùng có thể cần phối hợp với phương tiện bảo vệ mắt khác theo quy trình. Bất kỳ phương tiện nào cũng phải được đeo đúng vị trí và không cản tầm nhìn trong thao tác.",
        "Tuân thủ quy trình kiểm soát nhiễm khuẩn của đơn vị cho từng kỹ thuật; chọn kính hoặc tấm chắn đúng nguy cơ và kiểm tra sự vừa vặn. Lau, khử khuẩn hoặc thay theo hướng dẫn của nhà sản xuất và bệnh viện, đặc biệt giữa các lượt sử dụng. Tránh chạm tay bẩn lên bề mặt trong của kính, và tháo phương tiện bảo hộ theo đúng thứ tự để hạn chế tự nhiễm bẩn.",
        "Nếu dịch cơ thể hoặc hóa chất bắn vào mắt, báo sự cố, rửa theo quy trình của cơ sở và liên hệ bộ phận sức khỏe nghề nghiệp ngay. Nếu có đau, đỏ, nhìn mờ hoặc sợ sáng, cần khám mắt; không tự đánh giá nguy cơ nhiễm trùng chỉ từ cảm giác ban đầu.",
        "Kính cận có đủ chống giọt bắn khi làm thủ thuật?",
        "Không nên coi là đủ. CDC phân biệt kính thông thường với kính bảo hộ chống bắn; cần áp dụng quy trình của cơ sở cho thao tác cụ thể.",
        "https://www.cdc.gov/niosh/ppe/eye-safety/infection-control.html",
        "/kien-thuc/deo-kinh-bao-ho-dung-cach/",
    ),
    (
        "Kính bảo hộ bị mờ hơi nước hoặc trầy: khi nào cần chỉnh và thay?",
        "kinh-bao-ho-bi-mo-hoac-tray",
        "Kính bảo hộ chỉ có ích khi người dùng vẫn nhìn rõ và sẵn sàng đeo suốt công đoạn nguy cơ. Tròng mờ, trầy nhiều hoặc gọng lỏng có thể khiến người lao động tháo kính đúng lúc cần bảo vệ.",
        "Hơi nước trên kính có thể liên quan đến chênh lệch nhiệt độ, thông khí, khẩu trang hoặc độ ôm. Vết trầy làm tán xạ ánh sáng, nhất là ở môi trường cần nhìn chi tiết. Việc tự khoan lỗ, cắt gọng hoặc tháo chắn bên có thể làm mất tính năng bảo vệ của sản phẩm; cũng không nên lau bằng dung môi không được nhà sản xuất cho phép.",
        "Chọn loại bảo hộ được đánh giá cho mối nguy và điều kiện làm việc, thử độ vừa và phối hợp khẩu trang đúng cách. Vệ sinh theo hướng dẫn, dùng giải pháp chống mờ được cho phép và thay tròng/gọng hỏng. Báo bộ phận an toàn nếu kính không thể đeo thoải mái suốt ca để đổi mẫu phù hợp, thay vì bỏ kính. Kiểm tra lại tầm nhìn ngoại vi trước khi thao tác với máy.",
        "Nếu mắt cộm, đau hoặc mờ sau một ca làm việc nguy cơ, đừng chỉ đổ cho kính bị mờ. Khi có vật bắn, hóa chất hoặc ánh sáng mạnh tiếp xúc, cần xử trí theo loại sự cố và khám khi có triệu chứng. Kính đã chịu va đập mạnh cũng cần được kiểm tra hoặc thay theo quy định.",
        "Có nên tiếp tục dùng kính đã nứt nhẹ?",
        "Không. Kính nứt hoặc biến dạng cần được thay theo quy trình an toàn của nơi làm việc trước công đoạn nguy cơ.",
        "https://www.osha.gov/eye-face-protection",
        "/kien-thuc/deo-kinh-bao-ho-dung-cach/",
    ),
    (
        "Làm việc trong kho lạnh: mắt cay và chảy nước có phải chỉ do nhiệt độ?",
        "lam-viec-trong-kho-lanh-mat-cay",
        "Không khí lạnh, luồng gió và việc chuyển nhanh giữa môi trường lạnh–ấm có thể làm mắt khó chịu. Nhưng cay, đỏ hoặc chảy nước mắt cũng có thể do khô mắt, bụi, kính bảo hộ không phù hợp hoặc nguyên nhân khác.",
        "Người làm kho lạnh thường vừa cần kính bảo hộ vừa cần nhìn rõ nhãn hàng, xe nâng và lối đi. Kính bị mờ khi ra vào kho có thể làm giảm an toàn thao tác. Cảm giác chảy nước mắt không loại trừ khô mắt: bề mặt mắt bị kích thích đôi khi khiến nước mắt phản xạ tiết nhiều hơn. Không tự chẩn đoán chỉ theo nhiệt độ tại thời điểm có triệu chứng.",
        "Kiểm tra luồng gió hướng vào mặt, chọn kính phù hợp nguy cơ công việc và có biện pháp chống mờ được nhà sản xuất cho phép. Tạm dừng thao tác nếu kính mờ che tầm nhìn; lau đúng cách ở nơi an toàn. Nghỉ nhìn gần và chớp mắt đầy đủ khi đọc nhãn hoặc màn hình trong kho. Nếu cần nhỏ mắt thường xuyên, trao đổi với bác sĩ thay vì tự tăng số lần dùng thuốc.",
        "Khám khi đỏ, cộm hoặc chảy nước kéo dài sau khi rời kho; đau, sợ sáng hay mờ một mắt cần được đánh giá sớm. Mang theo loại kính bảo hộ đang sử dụng và mô tả thời điểm triệu chứng xuất hiện để bác sĩ liên hệ với điều kiện làm việc.",
        "Chảy nước mắt trong kho lạnh chứng tỏ mắt không bị khô?",
        "Không. Chảy nước có thể là phản xạ khi bề mặt mắt bị kích thích; cần khám nếu hiện tượng tái diễn.",
        "https://www.nei.nih.gov/eye-health-information/eye-conditions-and-diseases/dry-eye",
        "/kien-thuc/chay-nuoc-mat-nhieu-khi-ra-gio-hoac-nang/",
    ),
    (
        "Thợ làm tóc và làm móng: bảo vệ mắt trước hóa chất, bụi mịn",
        "tho-lam-toc-lam-mong-bao-ve-mat",
        "Thuốc nhuộm, dung dịch tẩy, keo và bụi khi mài móng có thể tiếp xúc mắt theo cách khác nhau. Cách bảo vệ cần dựa vào sản phẩm đang dùng và thao tác thực tế, không chỉ dựa vào mùi mạnh hay yếu.",
        "Giọt hóa chất bắn trong lúc pha hoặc rửa tóc có thể gây kích ứng; bụi mịn khi mài có thể gây cộm. Một số trường hợp đỏ mắt lặp lại còn liên quan đến thông khí kém hoặc việc đưa tay dính sản phẩm lên mắt. Tự nhỏ thuốc 'chống đỏ' sau mỗi ca có thể che dấu một vấn đề cần đánh giá.",
        "Đọc nhãn và phiếu an toàn của sản phẩm, bố trí thông gió và dùng bảo vệ mắt phù hợp với nguy cơ bắn hoặc bụi. Rửa tay trước khi chạm mặt; không để chai hóa chất mở sát mép bàn. Chuẩn bị nguồn nước rửa mắt dễ tìm. Nếu hóa chất bắn vào mắt, rửa ngay bằng nhiều nước sạch và liên hệ cơ sở y tế, mang thông tin sản phẩm theo.",
        "Nếu đỏ, đau, cộm, nhìn mờ hoặc sợ sáng sau tiếp xúc, nên được khám; tiếp xúc hóa chất đậm đặc cần xử trí khẩn sau khi bắt đầu rửa. Nếu triệu chứng chỉ xuất hiện trong ca nhưng lặp lại nhiều ngày, hãy ghi lại sản phẩm và thời điểm để bác sĩ đánh giá, không tự quy kết một nguyên nhân duy nhất.",
        "Đeo kính thời trang khi mài móng đã đủ chưa?",
        "Không mặc nhiên. Cần chọn phương tiện bảo vệ mắt theo bụi hoặc chất lỏng bắn, độ ôm và quy trình an toàn tại nơi làm việc.",
        "https://www.cdc.gov/niosh/ppe/eye-safety/index.html",
        "/kien-thuc/bui-va-hoa-chat-trong-moi-truong-lam-viec/",
    ),
    (
        "Người giao hàng và lái xe ngoài trời: bảo vệ mắt khỏi gió, bụi và nắng",
        "giao-hang-lai-xe-bao-ve-mat",
        "Làm việc trên đường khiến mắt tiếp xúc đồng thời với gió, bụi, nắng và thay đổi ánh sáng. Cách xử lý cần tách khó chịu bề mặt mắt khỏi việc nhìn không rõ biển báo hoặc vật cản.",
        "Mắt chảy nước khi gặp gió có thể do kích thích bề mặt, nhưng cũng có thể đi cùng khô mắt hoặc vấn đề khác. Kính tối màu vào ban ngày không có nghĩa phù hợp khi trời tối; tròng xước hoặc bẩn cũng làm giảm chất lượng nhìn. Người phải điều khiển phương tiện cần ưu tiên thị lực rõ và an toàn giao thông, không chỉ cảm giác đỡ chói.",
        "Dùng kính chống UV có thông số rõ ràng khi làm ngoài trời, chọn gọng vừa và giữ tròng sạch; thay loại kính phù hợp khi ánh sáng yếu. Nếu phải đeo kính có độ, kiểm tra độ kính định kỳ theo triệu chứng và yêu cầu công việc. Nghỉ ở nơi an toàn trước khi lau kính hoặc xử lý mắt cộm; không vừa lái xe vừa dụi mắt. Khi bụi bắn vào mắt, ngừng xe an toàn rồi đánh giá.",
        "Đi khám nếu mắt đỏ kéo dài, đau, chảy nước một bên nhiều, hoặc nhìn mờ khi lái xe dù đã làm sạch kính. Mờ đột ngột, nhìn đôi hoặc mất vùng nhìn là lý do dừng lái và tìm chăm sóc y tế ngay, không cố hoàn tất chuyến đi.",
        "Kính chống nắng có thay kính bảo hộ chống mảnh bắn không?",
        "Không. Kính chống UV và kính bảo hộ cơ học phục vụ các nguy cơ khác nhau; chọn theo hoàn cảnh làm việc.",
        "https://www.nei.nih.gov/research-and-training/research-news/protecting-your-eyes-suns-uv-light",
        "/kien-thuc/lai-xe-ban-dem-nhin-kem/",
    ),
    (
        "Đau mắt sau sự cố tại nơi làm việc: khi nào không nên chờ hết ca?",
        "dau-mat-sau-su-co-noi-lam-viec",
        "Một cơn đau mắt sau mảnh bắn, hóa chất hoặc nguồn sáng mạnh cần được nhìn theo sự cố đã xảy ra, không chỉ theo mức đỏ nhìn thấy. Trì hoãn vì 'còn làm được việc' có thể bỏ lỡ thời gian sơ cứu.",
        "Chấn thương do vật bay có thể để lại dị vật rất nhỏ; hóa chất có thể gây tổn thương bề mặt dù đã rửa thấy bớt rát. Phơi sáng hàn có thể khiến triệu chứng xuất hiện muộn. Những tình huống này không xử trí giống nhau, vì vậy mô tả chính xác vật liệu, sản phẩm và thời gian tiếp xúc sẽ giúp nhân viên y tế quyết định bước kiểm tra.",
        "Nếu hóa chất bắn vào mắt, bắt đầu rửa ngay bằng nước sạch đang chảy và gọi hỗ trợ. Nếu vật sắc hoặc mảnh ghim vào mắt, không ấn, dụi hay tự lấy; che nhẹ và đến cơ sở cấp cứu. Nếu chỉ có bụi nhỏ gây cộm, có thể rửa nhẹ, nhưng triệu chứng còn lại phải được đánh giá. Báo sự cố cho người phụ trách an toàn và mang thông tin sản phẩm hoặc vật liệu đi cùng.",
        "Đau nhiều, giảm thị lực, sợ ánh sáng, nhìn đôi, không mở được mắt hoặc dị vật còn ghim đều cần khám khẩn. Không lái xe một mình nếu thị lực bị ảnh hưởng. Ngay cả khi mắt đỡ sau sơ cứu, hóa chất nguy cơ cao vẫn cần bác sĩ đánh giá theo tính chất tiếp xúc.",
        "Không thấy vết thương thì có thể làm tiếp?",
        "Không nên dựa vào bề ngoài. Hãy xử trí theo loại sự cố và tìm hỗ trợ y tế khi có đau, mờ hoặc tiếp xúc hóa chất.",
        "https://www.cdc.gov/niosh/ppe/eye-safety/index.html",
        "/kien-thuc/mat-bi-cham-thuong-do-vat-nhon/",
    ),
]
