"""Article-specific depth for the 15 workplace-eye guides.

Each item adds four substantial sections. Keep factual claims inside the
scope of the primary source assigned in articles.py; operational examples are
illustrations, not claims about this hospital or a particular employer.
"""

EXTRA = {
"man-hinh-bi-loa-khi-lam-viec": [
 ("Tự tìm nguồn lóa trước khi thay thiết bị", "Hãy ngồi ở đúng vị trí thường làm việc và nhìn màn hình khi một tài liệu nền trắng đang mở. Lần lượt tắt đèn bàn, kéo rèm rồi đổi góc màn hình một ít để xem mảng sáng nào biến mất. Nếu vệt lóa chỉ xuất hiện vào buổi chiều, nguồn có thể là cửa sổ hơn là chất lượng màn hình. Nếu hiện thành nhiều đốm sáng dưới đèn trần, thử thay vị trí hoặc hướng đèn. Cần quan sát cả tờ giấy, bàn kính, áo sáng màu và tường phía sau vì phản xạ từ các bề mặt này cũng có thể làm vùng nhìn khó chịu. Ghi lại giờ và chỗ ngồi gây lóa để trao đổi với người phụ trách nơi làm việc. Việc thay cặp kính ngay khi chưa tìm nguồn lóa vừa tốn kém vừa có thể bỏ sót nguyên nhân dễ chỉnh hơn. Khi giảm phản xạ, mục tiêu là đọc rõ chữ ở tư thế tự nhiên, không phải làm phòng tối hẳn hoặc đẩy màn hình lên mức sáng tối đa."),
 ("Bố trí ánh sáng theo công việc thực tế", "Người nhập liệu cần nhìn cả màn hình lẫn giấy in, nên ánh sáng bàn làm việc phải đủ đọc giấy nhưng không chiếu thẳng vào màn hình. Người chỉnh ảnh hoặc đọc số liệu có thể cần điều kiện khác; vì vậy không có một mức sáng chung cho toàn bộ văn phòng. Thử để cửa sổ ở bên cạnh thay vì ngay sau lưng hoặc đối diện màn hình, dùng rèm khi ánh nắng thay đổi và hướng đèn bàn xuống tài liệu. Màn hình bám dấu tay, bụi hoặc vết lau cũng có thể làm ánh sáng tán xạ; vệ sinh bằng vật liệu được nhà sản xuất khuyến nghị. Nếu đồng nghiệp dùng chung bàn, đánh dấu vị trí màn hình và đèn thuận tiện cho cả hai thay vì mỗi người tự tăng độ sáng. Sau khi chỉnh, làm việc thử trong một ca bình thường rồi hỏi: chữ đã dễ đọc hơn chưa, còn phải nheo mắt không, có cần cúi hoặc nghiêng đầu để tránh phản xạ không?"),
 ("Khi nào vấn đề không còn chỉ ở ánh sáng?", "Một mắt nhìn mờ hơn mắt còn lại, nhìn đôi, đau đầu rõ sau một thời gian đọc ngắn hoặc khó nhìn cả khi rời màn hình là tín hiệu cần xem xét rộng hơn. Kính có độ cũ, khô mắt hoặc vấn đề điều tiết đều có thể cùng tồn tại với lóa. Ngược lại, người có thị lực tốt vẫn có thể khó chịu nếu ánh sáng phản chiếu mạnh. Vì thế, kết quả của việc đổi góc màn hình chỉ là một phép thử môi trường, không phải cách chẩn đoán. Nếu phải phóng chữ ngày càng lớn hoặc đưa mặt sát màn hình mới đọc được, hãy mang kính đang dùng đến buổi khám và mô tả khoảng cách làm việc. Nếu triệu chứng xảy ra đột ngột, kèm đỏ đau hoặc mất vùng nhìn, không chờ một cuộc kiểm tra kính định kỳ. Những thay đổi môi trường có thể tiếp tục áp dụng, nhưng không nên dùng chúng để trì hoãn đánh giá y tế khi triệu chứng bất thường."),
 ("Một kế hoạch thử trong một tuần", "Ngày đầu, chụp lại vị trí màn hình, cửa sổ và đèn để có mốc so sánh. Hai ngày tiếp theo, thay một yếu tố mỗi lần: kéo rèm đúng giờ có nắng, chuyển đèn sang phía không phản chiếu hoặc tăng cỡ chữ. Không đổi tất cả cùng lúc vì sẽ khó biết điều gì giúp ích. Ghi ngắn thời điểm bắt đầu mỏi, tình trạng nhìn rõ, mức lóa và công việc đang làm; không cần tự chấm điểm thị lực. Nếu nơi làm việc có nhiều người gặp cùng một vệt phản xạ, hãy đề nghị đánh giá ánh sáng chung thay vì từng người tự mua phụ kiện. Sau một tuần, giữ những điều chỉnh có lợi và bỏ những cách làm khiến tư thế xấu hoặc màn hình quá tối. Nếu không cải thiện, dữ liệu này cũng hữu ích khi đi khám: bác sĩ có thể phân biệt khó chịu chỉ ở một nơi làm việc với triệu chứng xuất hiện cả lúc đọc sách, lái xe hay ở nhà."),
],
"vi-tri-man-hinh-va-goc-nhin": [
 ("Đo khoảng cách theo khả năng đọc, không theo thói quen cúi sát", "OSHA gợi ý màn hình thẳng trước người dùng và cách ít nhất khoảng 20 inch, tương đương gần 50 cm. Đây là điểm bắt đầu cho việc chỉnh chỗ ngồi, không phải chỉ định kính hay con số bắt buộc cho mọi màn hình. Hãy ngồi lưng tựa thoải mái rồi đưa màn hình đến khoảng cách có thể đọc chữ thường ở kích thước hợp lý. Nếu phải vươn cổ, trước tiên tăng cỡ chữ hoặc độ phóng đại. Nếu đưa màn hình xa hơn nhưng không còn đọc rõ, ghi lại khoảng cách thực tế để trao đổi khi khám. Với máy tính xách tay, bàn phím và màn hình gắn liền làm tư thế khó cân bằng; giá đỡ cùng bàn phím rời có thể hữu ích khi dùng nhiều giờ. Không nên kê màn hình cao đến mức phải ngửa đầu liên tục chỉ để tạo bàn làm việc trông gọn hơn."),
 ("Một màn hình và hai màn hình cần bố trí khác nhau", "Nếu chỉ dùng một màn hình, đặt phần đang đọc chính diện và giữ mép trên màn hình ngang hoặc thấp hơn tầm mắt. Với hai màn hình sử dụng ngang nhau, có thể đặt hai màn hình gần nhau và xoay nhẹ về phía người ngồi; nếu một màn hình là chính, đặt nó thẳng trước mặt. Mục tiêu là giảm số lần xoay cổ quá xa và hạn chế phải liếc qua vùng ánh sáng khác biệt liên tục. Người xử lý bảng tính lớn cần đủ chỗ để đọc cột cuối mà không nghiêng đầu; người họp trực tuyến nên đặt cửa sổ cuộc gọi gần vùng nhìn chính. Hãy thử một ca làm việc rồi quan sát vai, cổ và mắt, vì tư thế không dễ chịu thường xuất hiện trước khi người dùng tự nhận ra. Điều chỉnh ghế và bàn đi cùng với màn hình, không tách rời từng món."),
 ("Cỡ chữ, kính và vị trí tạo thành một hệ", "Khi chữ nhỏ, nhiều người tự động tiến sát màn hình. Điều đó không chứng minh mắt tăng độ; có thể đơn giản là phần mềm đang để cỡ chữ không phù hợp. Tăng cỡ chữ, dùng độ tương phản dễ đọc, điều chỉnh độ phóng đại của trình duyệt rồi mới đánh giá. Nếu vẫn khó đọc ở nhiều thiết bị và cả giấy in, nhu cầu khám thị lực rõ ràng hơn. Người đang dùng kính đọc sách có thể thấy khoảng cách màn hình dài hơn sách không thật rõ; hãy mang cả kính và thông tin khoảng cách đến bác sĩ để được tư vấn kính phù hợp. Không tự chọn một mức độ kính từ bảng trên mạng, vì hai người cùng tuổi có thể khác tật khúc xạ và nhu cầu công việc. Sau khi đổi kính hoặc đổi nơi làm việc, nên chỉnh lại màn hình; kính tốt không bù được tư thế ngồi quá gò bó."),
 ("Tự kiểm tra trước và sau khi đổi bàn", "Hãy ghi ba mốc: khoảng cách từ mắt đến màn hình, vị trí mép trên so với mắt và thời gian có thể đọc thoải mái trước khi phải nheo mắt. Sau khi đổi bàn, kiểm tra lại đúng cùng loại tài liệu trong một thời gian tương tự. Đừng chỉ dựa vào cảm giác ngày đầu vì ánh sáng ngoài trời, giấc ngủ và nội dung đang đọc có thể khác nhau. Nếu chỗ ngồi dùng chung, lưu lại cài đặt phóng đại và chiều cao để người sau không phải chịu tư thế của người trước. Khi thấy mỏi, đứng dậy, nhìn xa và chớp mắt vài lần thay vì chỉ đổi qua điện thoại ở cùng khoảng cách gần. Nếu triệu chứng một mắt rõ rệt, xuất hiện đột ngột hoặc kèm đau, quá trình thử tại nhà không thay thế việc đi khám."),
],
"kho-mat-trong-phong-dieu-hoa": [
 ("Vì sao phòng mát vẫn làm mắt khó chịu?", "Điều hòa làm thay đổi luồng không khí quanh nơi ngồi. Nếu gió hướng thẳng vào mặt, nước mắt ở bề mặt mắt có thể bay hơi nhanh hơn; khi nhìn màn hình lâu, số lần chớp mắt cũng thường giảm. Hai yếu tố cộng lại khiến người làm văn phòng thấy rát hoặc cộm vào buổi chiều. Tuy nhiên, chỉ vì triệu chứng nặng ở phòng điều hòa không có nghĩa điều hòa là nguyên nhân duy nhất. Mi mắt, kính áp tròng, thuốc đang dùng và tình trạng sức khỏe khác đều cần được hỏi khi khám. Một số người chảy nước mắt nhiều lại tưởng mình không thể bị khô mắt, trong khi bề mặt bị kích thích có thể gây chảy nước phản xạ. Thử đổi hướng gió là bước thực tế, nhưng hãy ghi lại triệu chứng ở nhà, ngoài trời và ngày nghỉ để nhìn ra xu hướng thật."),
 ("Thay đổi nhỏ trong ca làm việc", "Bắt đầu bằng việc chuyển hướng miệng gió hoặc đổi vị trí ngồi để không khí không phả vào mắt. Đặt nhắc nghỉ ngắn khi làm việc liên tục trên máy tính và chớp mắt trọn vẹn thay vì chỉ khép mi một phần. Để tài liệu ở độ cao phù hợp, tránh ngước nhìn màn hình quá cao nếu tư thế đó khiến mắt mở rộng hơn. Uống nước phù hợp với nhu cầu cơ thể là thói quen chung, nhưng không nên coi uống nhiều nước là cách chữa mọi dạng khô mắt. Nếu dùng kính áp tròng, hỏi người khám về thời gian đeo và điều kiện làm việc thay vì tự tăng nước nhỏ mắt vô hạn. Nơi làm việc có thể cân nhắc điều chỉnh thông khí chung khi nhiều người cùng khó chịu; không nên tự lắp thiết bị tạo ẩm không được bảo trì, vì nó cũng đặt ra vấn đề vệ sinh."),
 ("Thuốc nhỏ và những kỳ vọng dễ sai", "Nước mắt nhân tạo có thể được bác sĩ hoặc dược sĩ tư vấn cho một số tình huống, nhưng thành phần, chất bảo quản và số lần dùng cần phù hợp với người bệnh. Thuốc làm trắng mắt có thể giảm đỏ tạm thời mà không giải quyết nguyên nhân; thuốc chứa kháng sinh hay steroid càng không nên tự dùng cho triệu chứng chỉ được mô tả là khô. Nếu phải nhỏ nhiều lần mỗi ngày trong nhiều tuần, đó là thông tin quan trọng cần mang đến buổi khám. Ghi tên sản phẩm và số lần dùng để bác sĩ xem xét, kể cả khi mua không cần đơn. Không đưa đầu lọ chạm mắt hoặc dùng chung lọ với đồng nghiệp. Người đeo kính áp tròng cần kiểm tra sản phẩm có phù hợp với kính đang dùng. Mục tiêu của khám không chỉ là chọn lọ nhỏ, mà còn xác định mi mắt, lớp nước mắt và bề mặt giác mạc có vấn đề gì."),
 ("Nhật ký triệu chứng giúp buổi khám hiệu quả hơn", "Trong vài ngày, ghi thời điểm rát, cộm hoặc nhìn mờ; chỗ ngồi có luồng gió trực tiếp không; số giờ nhìn màn hình; có đeo kính áp tròng không; và triệu chứng giảm thế nào sau khi rời phòng. Có thể đánh dấu nếu chỉ một mắt nặng hơn, vì điều này không nên bỏ qua. Mang theo các lọ đang sử dụng, kể cả thuốc nhỏ mua ở hiệu thuốc. Nếu làm việc với hóa chất, khói hoặc bụi, nói rõ thay vì chỉ mô tả phòng lạnh. Đau, sợ ánh sáng hoặc thị lực giảm không nên theo dõi kéo dài ở nhà. Bác sĩ có thể khám bề mặt mắt và tư vấn cách dùng thuốc, kính hoặc thay đổi môi trường phù hợp; bảng ghi chép không phải để tự chẩn đoán mà để tránh bỏ sót thông tin."),
],
"kinh-ap-trong-khi-lam-viec-nhieu-bui": [
 ("Kính áp tròng và kính bảo hộ giải quyết hai việc khác nhau", "Kính áp tròng đặt trên bề mặt mắt để chỉnh thị lực, còn kính bảo hộ tạo hàng rào trước mảnh bắn, bụi hoặc chất lỏng. Vì vậy câu hỏi không phải chỉ là 'có được đeo lens khi đi làm hay không' mà là nguy cơ cụ thể trong công việc và phương tiện bảo vệ phù hợp. NIOSH không đưa ra lệnh cấm chung cho mọi người đeo kính áp tròng trong môi trường hóa chất, nhưng nhấn mạnh đánh giá nguy cơ, đào tạo và bảo hộ. Một xưởng lắp ráp sạch khác với nơi mài, cắt hoặc pha hóa chất; nội quy và người phụ trách an toàn cần hướng dẫn theo từng vị trí. Kính áp tròng cũng có thể gây khó chịu khi tay dính bụi, người đeo phải tháo lắp giữa ca hoặc không có khu vực vệ sinh sạch. Việc đeo được trong một ca không chứng minh an toàn cho mọi công đoạn."),
 ("Chuẩn bị trước ca để không phải xử lý bằng tay bẩn", "Trước khi vào vị trí làm việc, kiểm tra kính áp tròng còn trong thời hạn và mắt không đỏ, đau hoặc cộm. Mang theo kính gọng dự phòng, hộp đựng sạch và dung dịch đúng loại theo hướng dẫn chăm sóc kính; tuyệt đối không dùng nước máy để ngâm kính. Biết trước nơi rửa tay và chỗ thay kính có thể giữ sạch. Nếu phải đeo phương tiện bảo vệ hô hấp cùng kính bảo hộ, thử độ vừa trước ca để không phải liên tục chỉnh kính. Khi mắt cộm, rời khu vực bụi, rửa và lau khô tay rồi mới chạm vào kính áp tròng. Không cố làm việc tiếp bằng cách dụi mắt qua kính bảo hộ. Nếu tháo kính ra thấy vẫn đau hoặc mờ, cất kính đã tháo để người khám biết loại đang dùng và đi kiểm tra."),
 ("Nếu có hóa chất hoặc vật bắn, xử trí theo sự cố", "Hóa chất bắn vào mắt là tình huống phải rửa ngay bằng nước sạch đang chảy; không mất thời gian tìm gương hoặc hộp đựng kính. Nếu kính áp tròng tháo ra dễ trong khi đang rửa thì tháo, nhưng tiếp tục rửa và tìm chăm sóc y tế theo nguy cơ hóa chất. Vật sắc hoặc mảnh kim loại ghim vào mắt lại cần tránh ấn, dụi hoặc tự lấy. Hai tình huống không thể xử trí bằng cùng một mẹo. Báo cho nhân viên y tế rằng mình đeo kính áp tròng, loại công việc và chất tiếp xúc. Không tự đeo lại kính áp tròng ngay sau sự cố dù mắt đỡ cộm. Công việc cần được đánh giá lại để loại bảo hộ đang dùng che được hướng bắn thực tế, thay vì chỉ yêu cầu người lao động bỏ kính áp tròng mà giữ nguyên mối nguy."),
 ("Dấu hiệu cảnh báo riêng ở người đeo kính áp tròng", "Mắt đỏ một bên, đau tăng, sợ ánh sáng, tiết dịch hoặc giảm thị lực trong và sau ca là các dấu hiệu cần khám sớm. Người đeo kính áp tròng không nên tự điều trị bằng thuốc giảm đỏ hoặc đợi nhiều ngày xem có tự hết. Những triệu chứng này có thể liên quan đến bề mặt giác mạc, nhưng cần khám để xác định chứ không thể tự kết luận nhiễm trùng. Khi đi khám, mang theo kính áp tròng, hộp hoặc thông tin loại kính và dung dịch đang dùng nếu có thể. Nêu rõ có từng ngủ quên khi đeo kính, dùng quá hạn, tiếp xúc bụi hoặc tháo lắp trong môi trường không sạch không. Sau khi được xử trí, hỏi khi nào được trở lại dùng kính và có cần thay phương tiện bảo hộ tại nơi làm việc. Đừng chỉ đổi sang một loại lens khác mà bỏ qua nguyên nhân nguy cơ."),
],
"kinh-can-co-thay-kinh-bao-ho-duoc-khong": [
 ("Nhìn rõ và chống chấn thương là hai yêu cầu độc lập", "Kính cận được chọn để ánh sáng hội tụ đúng trên võng mạc, còn kính bảo hộ phải chịu được loại nguy cơ được đánh giá ở nơi làm việc. Tròng nhựa của kính thường không mặc nhiên đạt yêu cầu chống va đập, gọng thời trang có thể hở rộng hai bên, và kính dễ rơi khi cúi hay mang khẩu trang. Ngược lại, đưa cho người bị cận một kính bảo hộ không độ nhưng mờ tầm nhìn cũng không phải giải pháp tốt. Khi nhìn không rõ vạch cắt, biển báo hoặc máy chạy, người lao động có thể thao tác thiếu chính xác. Vì thế cần chọn phương án cho phép vừa nhìn rõ vừa được bảo vệ. OSHA nêu hai hướng thông dụng: kính bảo hộ tích hợp tròng có độ, hoặc kính bảo hộ phù hợp đeo ngoài kính có độ mà không làm xô lệch kính bên trong."),
 ("Chọn theo hướng bắn chứ không theo tên sản phẩm", "Mảnh kim loại từ máy mài, bụi mịn khi chà nhám và dung dịch tẩy bắn từ bồn rửa là ba nguy cơ khác nhau. Kính có chắn bên có thể quan trọng khi vật bay từ nhiều hướng; kính chống bắn chất lỏng lại cần kiểu che khác. Tấm chắn mặt có thể bảo vệ vùng mặt rộng hơn nhưng không phải lúc nào thay được kính bảo hộ chính cho mắt. Người quản lý an toàn phải đánh giá công việc và hướng dẫn loại phù hợp; nhân viên nên hỏi vì sao mẫu được phát đáp ứng công đoạn của mình. Thử kính khi đeo cùng kính cận, khẩu trang và mũ bảo hộ thực tế. Nếu gọng ngoài ép kính cận vào sống mũi, tạo hơi nước hoặc che tầm nhìn bên, cần đổi mẫu. Không tự tháo chắn bên cho thoải mái nếu đó là phần cần để bảo vệ."),
 ("Kiểm tra trước ca và sau va đập", "Hãy nhìn tròng trước nguồn sáng: vết nứt, trầy nhiều, mờ đục hoặc chốt lỏng là lý do báo đổi kính. Kiểm tra phần chắn bên còn nguyên và gọng giữ kính ổn định khi cúi. Lau theo hướng dẫn nhà sản xuất, không dùng dung môi mạnh theo suy đoán vì có thể làm hỏng lớp phủ. Khi kính chịu va đập từ vật bắn, dù mắt không đau, vẫn xem lại kính trước khi dùng tiếp theo quy trình an toàn. Nếu kính bảo hộ có độ được cấp riêng cho một người, không đưa cho đồng nghiệp có độ khác mượn. Người đeo kính áp tròng cũng cần bảo hộ như người không đeo. Mọi lần phải tháo kính vì mờ hơi nước, đau tai hoặc khó nhìn nên được báo lại để cải tiến lựa chọn và độ vừa; việc có kính trên giấy tờ không đủ nếu người lao động không thể dùng nó suốt công đoạn."),
 ("Khi xảy ra sự cố dù đã đeo kính", "Nếu mảnh bắn lọt qua mép kính và mắt đau hoặc cộm, ngừng máy, không dụi mắt và đánh giá tại cơ sở y tế nếu triệu chứng không hết. Nếu nghi vật sắc ghim vào mắt, không ấn, tự lấy hoặc rửa mạnh; che bảo vệ nhẹ và đi cấp cứu. Với hóa chất bắn, rửa mắt ngay bằng nhiều nước sạch, sau đó tìm hỗ trợ y tế. Mang theo kính bị va chạm nếu việc này an toàn, vì hình dạng hỏng có thể giúp đánh giá đường bắn. Sau xử trí, cơ sở làm việc nên xem lại chắn máy, quy trình và loại kính; thay một tròng kính không đủ nếu mối nguy ban đầu vẫn còn. Khi đi khám thị lực định kỳ, nói rõ công việc cần nhìn xa, nhìn gần hay khoảng cách trung gian để kính có độ và kính bảo hộ phối hợp phù hợp."),
],
}
