"""Final distinct context sections bringing each long-form guide near 1,500 words."""

MORE = {
"mai-khoan-kim-loai-bao-ve-mat": [
 ("Một buổi trao đổi ngắn trước công đoạn mới", "Nếu hôm nay xưởng nhận vật liệu mới hoặc chuyển từ mài sang cắt, hãy dành vài phút nói rõ mảnh có thể bay theo hướng nào, ai đang đứng gần và kính hiện có còn phù hợp không. Người hướng dẫn có thể cho thợ mới quan sát thao tác an toàn từ ngoài vùng nguy cơ trước khi tự cầm máy. Đừng giả định họ biết cách phân biệt kính bảo hộ với kính cận chỉ vì đã từng làm ở xưởng khác. Cần chỉ điểm rửa mắt, số gọi hỗ trợ và cách dừng máy khi có sự cố. Nếu người lao động thấy kính che cạnh nhưng không nhìn rõ vạch cắt, phải giải quyết trước khi vận hành. Ghi phản ánh về độ mờ, cấn hoặc trượt để lần cấp phát sau chọn đúng cỡ. Sau ca, hỏi có mảnh bay qua khu vực người quan sát hay không; một lần suýt trúng mắt là dữ kiện cần sửa quy trình. Thay đổi nhỏ trước công đoạn thường dễ làm hơn xử lý hậu quả sau tai nạn."),
],
"nuoc-tay-rua-ban-vao-mat-khi-lam-viec": [
 ("Khác biệt giữa khó chịu nhẹ và tiếp xúc hóa chất", "Mắt cay trong phòng có mùi tẩy rửa không chứng minh đã có dung dịch vào mắt; ngược lại, một giọt bắn rõ ràng cần xử lý ngay dù lúc đầu chưa đau nhiều. Hãy hỏi cụ thể có nhìn thấy giọt bắn không, sản phẩm gì đang dùng, mắt nào bị và người lao động đã xối rửa chưa. Nếu có tiếp xúc trực tiếp, ưu tiên quy trình sơ cứu hóa chất, không chờ thử xem mắt có đỏ hơn không. Nếu khó chịu xuất hiện dần ở nhiều người mà không có giọt bắn, cần đánh giá điều kiện thông gió, thao tác và sản phẩm đang sử dụng. Đừng dùng một câu trả lời chung cho cả hai tình huống. Sau sự cố, người bệnh nên được hướng dẫn nơi khám và cách trình bày thông tin sản phẩm. Cơ sở nên giữ sẵn bảng dữ liệu an toàn để không phải lục tìm trên mạng khi đang cấp cứu. Việc phân loại đúng giúp vừa xử trí kịp thời cho cá nhân vừa sửa môi trường cho nhóm."),
],
"bui-xi-mang-vao-mat-cong-truong": [
 ("Đừng dựa vào việc mắt đã bớt đỏ", "Sau khi rửa, người lao động có thể thấy dễ chịu hơn và muốn trở lại công việc. Tuy nhiên, cảm giác ban đầu không cho biết chắc còn hạt dưới mí hay tổn thương bề mặt mắt. Nếu có tiếp xúc rõ với xi măng, đặc biệt vữa ướt hoặc lượng bột lớn, cần trình bày tình huống với nhân viên y tế để được hướng dẫn khám phù hợp. Không tự dùng thuốc nhỏ còn từ lần đau mắt trước hoặc thuốc của đồng nghiệp. Khi đi khám, mang theo thông tin loại xi măng nếu có, kể cả việc vật liệu đã pha thêm phụ gia. Nếu thị lực giảm hoặc đau tăng khi trên đường, báo ngay. Người giám sát nên sắp xếp người khác thay công đoạn nguy cơ, tránh tạo áp lực quay lại sớm. Lần kiểm tra y tế cũng là dịp ghi nhận liệu công trường có thiếu điểm rửa mắt, kính đúng cỡ hoặc che chắn tại nguồn không. Bớt đỏ là tin tốt, nhưng không phải giấy chứng nhận mắt đã an toàn."),
],
"phun-thuoc-bao-ve-thuc-vat-bao-ve-mat": [
 ("Kế hoạch khi làm việc ở nơi xa", "Ở ruộng hoặc vườn xa nhà, một chai nước nhỏ có thể không đủ cho tình huống cần xối rửa mắt. Trước khi phun, hãy xác định nguồn nước sạch, người có thể giúp, phương tiện liên lạc và đường đến cơ sở y tế. Làm việc một mình cần phương án báo vị trí nếu không thể tự điều khiển xe. Nhãn thuốc nên ở nơi dễ tìm, không để trong kho khóa mà chỉ một người giữ chìa. Khi bình rò, người phun phải có quyền dừng việc để sửa, không cố dùng hết phần thuốc còn lại. Trang bị bảo hộ cần được kiểm tra trong điều kiện trời nóng thật, vì thiết bị khó chịu dễ bị tháo bỏ giữa ca. Người tổ chức công việc nên tính thời gian nghỉ và thay thiết bị nếu bị bẩn. Sự chuẩn bị này giúp phản ứng nhanh hơn khi có giọt bắn, đồng thời giảm khả năng xảy ra sự cố từ đầu."),
],
"lam-viec-ngoai-troi-bao-ve-mat-tia-uv": [
 ("Khi phải kết hợp kính râm và kính bảo hộ", "Một người giám sát công trường có thể cần vừa chống chói vừa tránh mảnh bắn; người làm vườn có thể cần chắn cành cây và tia UV. Hai yêu cầu không tự được đáp ứng bằng một kính râm thời trang. Hãy mô tả công việc cho người phụ trách an toàn hoặc nơi cung cấp kính để chọn sản phẩm có thông tin bảo vệ phù hợp, độ che cạnh và khả năng nhìn rõ. Nếu phải đeo kính cận, cần thử cả ba yếu tố: độ nhìn, chống UV và bảo vệ cơ học. Tròng tối có thể gây khó nhìn chi tiết trong bóng râm; tròng quá sáng có thể khó chịu khi ra vùng phản chiếu. Nên thử trong các điểm làm việc điển hình trước khi cấp đồng loạt. Nếu một mẫu khiến nhiều người phải tháo khi cúi hoặc bị mờ cùng mũ bảo hiểm, tìm mẫu khác. An toàn mắt cần theo hoạt động thực tế, không theo hình thức của kính."),
],
"nhan-vien-y-te-kinh-bao-ve-mat-giot-ban": [
 ("Vai trò của người quản lý khoa", "Kính đúng loại sẽ ít được dùng nếu nằm trong kho xa phòng thủ thuật, thiếu cỡ hoặc không có quy trình làm sạch sau ca. Người quản lý cần bố trí nơi cấp phát dễ thấy, thiết bị dự phòng khi bị bẩn, và hướng dẫn rõ loại dùng một lần với loại tái sử dụng. Quan sát vài ca thực tế để biết nhân viên có phải tháo kính vì mờ, kính va khẩu trang hay trượt khi cúi không. Nếu có, hãy sửa thiết bị hoặc bố trí công việc thay vì chỉ nhắc tuân thủ. Các trường hợp giọt bắn vào mắt cần được báo cáo để đánh giá phơi nhiễm kịp thời và học từ sự cố. Người mới hoặc người luân chuyển khoa phải biết tuyến báo cáo, vì họ có thể không quen tên gọi thiết bị tại đơn vị. Truyền thông rõ ràng giúp bảo vệ mắt trở thành thao tác thường quy, không phải lựa chọn khi có thời gian."),
],
"kinh-bao-ho-bi-mo-hoac-tray": [
 ("Kính dự phòng nên nằm ở đâu?", "Nếu kính duy nhất bị mờ, nứt hoặc dây đứt giữa ca, người lao động cần biết nơi nhận kính khác ngay. Cất kính dự phòng ở kho khóa xa công đoạn có thể khiến họ tiếp tục làm việc không bảo hộ. Nơi cấp phát nên rõ người phụ trách, có đủ cỡ và cho phép đổi nhanh khi kính không vừa. Mẫu thử cần được kiểm tra độ trong, mức che chắn và tương thích với khẩu trang, mũ trước khi đưa vào sử dụng rộng. Những chiếc kính trả lại vì xước nên được tách khỏi thiết bị còn tốt để tránh phát lại. Theo dõi lý do đổi giúp phát hiện một lô kém chất lượng hoặc cách vệ sinh làm hỏng lớp phủ. Người quản lý cần xem chi phí kính thay thế cùng chi phí rủi ro khi thị lực bị cản trở; trì hoãn đổi một tròng xước không phải tiết kiệm hợp lý. Quy trình đổi rõ ràng cũng khuyến khích báo hỏng sớm."),
],
"lam-viec-trong-kho-lanh-mat-cay": [
 ("Sự khác nhau giữa các vị trí trong cùng kho", "Một người đứng kiểm hàng ngay trước dàn lạnh có thể chịu luồng gió nhiều hơn người lái xe nâng ở lối khác; người đọc nhãn lại tập trung nhìn gần lâu hơn người chỉ di chuyển hàng. Vì vậy, khi khảo sát phản ánh về mắt, nên ghi công đoạn, vị trí và thời gian, thay vì gộp mọi nhân viên kho thành một nhóm. Có thể thử luân phiên vị trí hoặc chỉnh hướng gió theo quy định kỹ thuật rồi theo dõi triệu chứng. Không tự che miệng thổi hoặc thay hệ thống lạnh khi chưa có người có chuyên môn đánh giá, vì an toàn hàng hóa và nhiệt độ cũng phải bảo đảm. Nếu chỉ một người bị cay mắt, vẫn nên lắng nghe và khuyến khích khám khi cần; bệnh mắt cá nhân không bị loại trừ bởi việc đồng nghiệp không sao. Dữ liệu cụ thể giúp vừa cải thiện môi trường vừa hỗ trợ bác sĩ đánh giá người bệnh."),
],
"tho-lam-toc-lam-mong-bao-ve-mat": [
 ("Khách hàng cũng cần được bảo vệ", "Một thao tác làm tóc hoặc móng có thể đặt mặt khách ở gần chai dung dịch, bụi hoặc dụng cụ. Hãy bố trí bàn và ghế để hướng rót, phun hoặc mài không thẳng về mắt khách; giải thích trước công đoạn dễ bắn và mời khách giữ vị trí phù hợp. Nếu cần, dùng biện pháp che chắn được cơ sở đánh giá. Khi khách báo cay hoặc có giọt bắn, dừng dịch vụ, sơ cứu theo nhãn sản phẩm và hướng dẫn y tế, không cố hoàn tất để tránh chậm lịch. Ghi sản phẩm đã dùng và thời điểm sự cố, cung cấp thông tin đó cho khách khi đi khám. Việc xin lỗi không thay thế xử trí đúng. Sau sự cố, xem lại hướng thao tác và bàn làm việc để bảo vệ khách tiếp theo. Một quy trình chú ý cả người thợ lẫn khách làm chất lượng dịch vụ tốt hơn và giảm việc bỏ sót người có nguy cơ."),
],
"giao-hang-lai-xe-bao-ve-mat": [
 ("Khi lịch chạy tạo áp lực bỏ qua triệu chứng", "Người giao hàng có thể ngại dừng vì sợ trễ đơn, nhưng thị lực kém ảnh hưởng trực tiếp đến khả năng quan sát xe và người đi đường. Người điều phối nên có quy trình cho phép báo mắt bị vật bắn, kính chắn hỏng hoặc nhìn mờ, rồi chuyển đơn sang người khác khi cần. Không yêu cầu người lái tự chứng minh mức nguy hiểm bằng cách tiếp tục chạy thử. Sau khi dừng ở vị trí an toàn, họ cần được hỗ trợ liên hệ cơ sở y tế và phương án di chuyển nếu không thể tự lái. Với khó chịu tái diễn cuối ca, có thể xem lại lịch nghỉ, điều kiện gió bụi và thiết bị bảo vệ, nhưng vẫn khuyến khích khám nếu triệu chứng kéo dài. Việc quản lý chuyến hàng nên ghi nhận sự cố mà không trừng phạt người báo sớm. Một đơn giao muộn có thể xử lý; tai nạn khi tầm nhìn không rõ có thể gây hậu quả lớn hơn."),
],
}
