"""Article-specific long-form guidance for cold storage, salons, and driving."""

MORE = {
"lam-viec-trong-kho-lanh-mat-cay": [
 ("Điều gì thay đổi khi đi qua cửa kho lạnh?", "Người làm kho có thể liên tục đi giữa khu vực lạnh, khô và nơi ấm, ẩm hơn. Không khí thổi từ dàn lạnh, luồng gió ở cửa và việc tập trung đọc mã hàng đều có thể làm mắt khó chịu. Triệu chứng cay hoặc chảy nước không đủ để kết luận nguyên nhân là nhiệt độ; khô mắt, kích ứng bụi, kính áp tròng hoặc bệnh mắt khác vẫn cần được cân nhắc. Hãy ghi rõ triệu chứng xuất hiện khi ở trong kho, lúc bước ra ngoài hay chỉ sau nhiều giờ nhìn nhãn nhỏ. Nếu một mắt bị nhiều hơn hoặc nhìn mờ, đừng giải thích đơn giản bằng không khí lạnh chung cho cả hai mắt. Người lao động có thể thử thay vị trí đứng khỏi luồng gió trực tiếp và nghỉ ở khu vực phù hợp, nhưng khi đau, đỏ hoặc triệu chứng kéo dài vẫn nên khám. Quan sát điều kiện cụ thể giúp bác sĩ và người phụ trách an toàn tìm đúng vấn đề."),
 ("Bố trí luồng gió và công việc đọc nhãn", "Không nên đặt chỗ quét mã hoặc kiểm hàng ngay trước luồng khí thổi mạnh nếu có thể sắp xếp khác. Khi cần đọc nhiều nhãn nhỏ, bảo đảm đủ ánh sáng và cỡ chữ trên thiết bị cầm tay phù hợp để người lao động không phải đưa mặt sát vào hàng. Đọc khó có thể do mờ kính khi đổi nhiệt độ, do chữ in quá nhỏ hoặc do thị lực cần kiểm tra; hãy tách từng khả năng. Khi ra vào kho, dành khoảng thời gian an toàn để kính thích nghi và lau theo hướng dẫn thay vì tháo kính ở khu vực vẫn có nguy cơ va đập. Nếu nhiều người cùng phản ánh mắt cay ở một vị trí, xem lại hướng gió hoặc thông gió của khu vực. Việc chỉnh điều kiện chung có thể giảm khó chịu cho cả ca, trong khi một lọ thuốc nhỏ của từng người không thay đổi môi trường."),
 ("Kính áp tròng và kính bảo hộ trong kho", "Kính áp tròng có thể làm một số người cảm thấy khó chịu hơn trong môi trường khô, nhưng mức độ khác nhau giữa từng người. Người đang dùng kính nên tuân thủ thời gian đeo, chăm sóc bằng tay sạch và mang kính gọng dự phòng nếu công việc cho phép. Kính bảo hộ được dùng khi có nguy cơ va đập, bụi hoặc hóa chất theo đánh giá nơi làm việc; kính gọng điều chỉnh thị lực không mặc nhiên thay thế bảo hộ. Thử kính cùng mũ, khẩu trang và đồ giữ ấm để tránh thiết bị xô lệch. Khi kính đọng sương, dừng thao tác cần nhìn rõ ở vị trí an toàn, lau và điều chỉnh; đừng tiếp tục lái xe nâng hoặc mang hàng cồng kềnh khi không nhìn rõ. Nếu mắt cộm, không dụi bằng găng vừa cầm kiện hàng. Rửa tay trước khi chạm vào mắt hoặc tháo kính áp tròng là bước nhỏ nhưng quan trọng."),
 ("Theo dõi bằng nhật ký ngắn", "Ghi ca nào, vị trí nào, thời gian ở kho bao lâu, có dùng màn hình hay quét mã không, mắt nào cay và triệu chứng kéo dài bao lâu sau khi ra ngoài. Sau đó thử một thay đổi trong vài ngày: tránh luồng gió, điều chỉnh màn hình, lau kính đúng cách hoặc dùng kính gọng thay kính áp tròng khi được phép. Nếu thay nhiều thứ cùng lúc, khó biết điều nào có ích. Người phụ trách có thể so sánh phản ánh từ nhiều vị trí, nhưng không nên suy rằng mọi người giống nhau. Bệnh mắt có thể xuất hiện ở một cá nhân dù các đồng nghiệp không có triệu chứng. Nếu triệu chứng thường xuyên cần thuốc nhỏ, người lao động nên hỏi bác sĩ hoặc dược sĩ về sản phẩm phù hợp và khám khi không cải thiện. Không tự dùng thuốc làm hết đỏ kéo dài để che biểu hiện trong ca."),
 ("Khi nào phải rời công việc để khám?", "Đau rõ, đỏ tăng, nhìn mờ, sợ ánh sáng, chấn thương hoặc triệu chứng chỉ một mắt kéo dài là lý do không nên chờ hết ca. Người vận hành xe nâng, dao cắt hoặc thiết bị cần nhìn chính xác càng không nên tiếp tục khi thị lực giảm. Nếu chỉ cay nhẹ thoáng qua, có thể xem lại luồng gió và thói quen làm việc, nhưng vẫn cần theo dõi diễn biến. Khi đi khám, kể điều kiện kho, thời gian triệu chứng, có đeo kính áp tròng không, đã dùng thuốc nhỏ gì và mắt có đỡ khi nghỉ không. Không tự gắn nhãn ‘dị ứng lạnh’ hay ‘khô mắt’ chỉ từ cảm giác. Bác sĩ có thể khám bề mặt nhãn cầu, thị lực và các nguyên nhân phù hợp với triệu chứng. Sau khi khám, tuân thủ hướng dẫn điều trị và thông tin cần thiết cho người quản lý để bố trí công việc an toàn."),
 ("Một quy trình cho nhóm kho", "Trước ca, xác định công đoạn phải đọc chi tiết, điểm có gió thổi trực tiếp, nơi làm sạch kính và cách báo khi nhìn kém. Dự phòng kính bảo hộ đủ cỡ, sạch và không xước; đào tạo người mới cách xử trí nếu mắt bị vật bắn hoặc hóa chất rò từ hàng hóa. Không dùng khăn chung bẩn để lau tròng và mắt. Ca đêm cần ánh sáng đủ ở khu vực kiểm hàng, nhưng tránh đèn phản chiếu thẳng vào mắt người đọc mã. Khi có một người phản ánh mắt cay, hỏi tình huống cụ thể thay vì chỉ phát thuốc nhỏ. Nếu có nhiều phản ánh, cần xem môi trường chung và tham khảo bộ phận an toàn lao động. Một kế hoạch tốt giúp người lao động giữ mắt dễ chịu và nhìn rõ để làm việc chính xác, đồng thời phát hiện được dấu hiệu y khoa cần khám sớm."),
],
"tho-lam-toc-lam-mong-bao-ve-mat": [
 ("Nguy cơ khác nhau ở từng công đoạn", "Trong tiệm tóc và tiệm móng, nguy cơ với mắt không chỉ từ một chai hóa chất. Bụi khi mài móng, giọt khi pha thuốc nhuộm hoặc dung dịch xử lý, hơi bay trong không gian kín và việc chạm tay dính sản phẩm lên mắt là các tình huống khác nhau. Hãy liệt kê công đoạn nào làm vật liệu văng, ở khoảng cách nào và ai đứng bên cạnh, rồi chọn biện pháp tương ứng. Không phải mọi sản phẩm đều gây cùng tổn thương; nhãn và bảng an toàn của sản phẩm đang dùng là nguồn quan trọng. Người làm ở tiệm nhỏ vẫn cần biết điểm nước sạch để rửa mắt và cách gọi hỗ trợ, không nên nghĩ quy trình này chỉ dành cho nhà máy. Nếu có người liên tục cay mắt cuối ca, đánh giá cả bụi, thông gió, kính bảo vệ và thói quen dụi mắt, không tự chẩn đoán chỉ từ nghề nghiệp."),
 ("Bụi mài móng có thể đi đâu?", "Bụi phát sinh gần mặt người thợ và khách, đặc biệt khi mắt tập trung sát vùng thao tác. Thu gom bụi tại nguồn bằng thiết bị phù hợp và vệ sinh bề mặt theo quy trình giúp giảm vật liệu phát tán; đừng dùng luồng khí mạnh thổi bụi từ bàn lên mặt. Kính bảo hộ thích hợp cần che vùng mắt mà vẫn nhìn rõ chi tiết nhỏ. Nếu kính mờ hoặc xước làm phải cúi sát hơn, báo thay loại phù hợp thay vì bỏ kính. Rửa tay trước khi tháo kính áp tròng hoặc dụi mắt, vì bụi có thể bám lên găng, dụng cụ và điện thoại. Sau ca, làm sạch bàn, kính và vật dụng theo hướng dẫn để bụi không tích lũy rồi phát tán ở ca sau. Nếu mắt cộm kéo dài, đau, đỏ hoặc nhìn mờ, cần khám để loại trừ dị vật hay tổn thương bề mặt."),
 ("Pha và dùng sản phẩm hóa chất", "Đọc nhãn để biết cách pha, dùng và xử trí khi sản phẩm bắn vào mắt. Không pha hai chất vì kinh nghiệm truyền miệng, không chuyển sang chai đồ uống và không bỏ nhãn khi chia nhỏ. Đặt bát hoặc chai ở vị trí chắc, rót chậm và giữ mặt tránh hướng bắn. Găng tay phù hợp giúp giảm tiếp xúc da nhưng có thể mang hóa chất lên mắt nếu người thợ vô thức lau mồ hôi hoặc chỉnh kính; cần thay hoặc làm sạch theo quy trình. Kính bảo vệ mắt nên tương thích với khẩu trang và ánh sáng chỗ làm. Khách cũng có thể ở trong vùng giọt bắn, nên cách bố trí ghế, tấm che và thao tác phải tính cho cả hai người. Nếu xảy ra sự cố, bắt đầu rửa mắt bằng nước sạch ngay theo hướng dẫn sản phẩm và tìm trợ giúp y tế; đừng chờ xác định chính xác tên hóa chất rồi mới rửa."),
 ("Thông gió và điều kiện nhìn", "Không gian tiệm có nhiều người và nhiều thao tác liên tiếp; mùi nồng không phải thước đo duy nhất của nguy cơ, còn một tiệm không có mùi cũng không tự bảo đảm an toàn. Việc chọn hệ thống thông gió cần dựa trên sản phẩm và quy mô công việc, có người chuyên trách tư vấn khi cần. Với mắt, luồng quạt thổi trực tiếp cũng có thể làm khó chịu, nên cần bố trí vừa giảm phát tán vừa không đưa bụi qua mặt người thợ. Đèn đủ sáng và không chói giúp đọc nhãn, phân biệt màu và thao tác chính xác mà không phải cúi gần khách. Khi người làm than mắt khô, ghi xem triệu chứng gắn với công đoạn mài, pha hóa chất hay cả lúc không làm việc. Thay một yếu tố và quan sát trước khi kết luận. Nếu triệu chứng tăng hoặc có đau, cần khám mắt thay vì chỉ đổi sang một loại thuốc nhỏ khác."),
 ("Xử lý sự cố và ghi lại sản phẩm", "Nếu bột, vụn hoặc chất lỏng vào mắt, dừng thao tác ngay. Với hóa chất, xối rửa sớm theo nhãn và hướng dẫn cấp cứu; tránh dùng dung dịch tự pha để trung hòa. Với vật cắm hoặc va đập mạnh, không tự lấy ra hay ấn lên mắt, cần được khám khẩn. Đừng dụi hoặc để đồng nghiệp dùng que bông kiểm tra sâu. Chụp nhãn sản phẩm, ghi tên, thời điểm tiếp xúc, mắt bị, bước sơ cứu và triệu chứng sau đó để mang đi khám. Người quản lý nên giúp khách hoặc nhân viên đi cơ sở y tế khi cần, đồng thời cất thông tin lô sản phẩm nếu liên quan. Sau sự cố, xem lại chai lọ, hướng thao tác, kính, quạt, vị trí khách và điểm rửa mắt. Việc ghi chép có ích cho phòng ngừa hơn là tìm ai đáng trách. Người bị thương cần theo đúng hướng dẫn tái khám dù triệu chứng ban đầu đã giảm."),
 ("Bảo vệ người mới vào nghề", "Người học việc có thể bắt chước thao tác nhanh của đồng nghiệp mà chưa biết sản phẩm nào cần bảo vệ mắt. Trước khi giao việc, nên hướng dẫn đọc nhãn, chọn găng và kính, vị trí nước rửa mắt và ai được gọi khi xảy ra sự cố. Cho họ thực hành bố trí bàn mài, chai hóa chất và dụng cụ trước khi có khách, để không phải vừa đoán vừa thao tác trong giờ đông. Kính phải vừa khuôn mặt; một chiếc kính dùng chung xước hoặc bẩn dễ khiến người mới bỏ qua. Dạy cách chạm vào mặt an toàn sau khi tháo găng và rửa tay. Khi họ báo kính mờ hay mắt cay, hãy xem đây là thông tin cải thiện nơi làm việc. Văn hóa hỏi và báo sớm sẽ giúp phòng một sự cố lớn hơn, nhất là khi tiệm thay sản phẩm hoặc thêm dịch vụ mới."),
],
"giao-hang-lai-xe-bao-ve-mat": [
 ("Nhìn rõ là yêu cầu an toàn đầu tiên", "Người giao hàng phải đọc biển đường, quan sát gương, đánh giá khoảng cách và phản ứng khi ánh sáng thay đổi. Kính râm, kính chắn gió, kính cận hoặc mũ bảo hiểm chỉ hữu ích nếu vẫn giữ được tầm nhìn rõ. Một tròng quá tối trong bóng râm, kính trầy trước vùng nhìn hoặc mặt chắn đọng sương có thể làm thao tác kém an toàn. Trước khi đi, thử nhìn biển số, đèn tín hiệu và gương ở khoảng cách thực tế. Nếu thường xuyên nheo mắt dù đã giảm chói, hãy kiểm tra thị lực thay vì mua thêm kính râm. Người có độ cận cần dùng kính đúng nhu cầu lái xe theo tư vấn chuyên môn. Khi thị lực đột ngột giảm, nhìn đôi hoặc đau mắt, không tiếp tục chạy chuyến chỉ để kịp đơn hàng. Sức khỏe mắt và an toàn giao thông liên quan trực tiếp trong công việc này."),
 ("Nắng, gió và bụi có thể xuất hiện cùng lúc", "Nắng chiếu từ phía trước hoặc phản xạ từ mặt đường làm người lái khó chịu; gió và bụi khi chạy xe máy có thể khiến mắt cay, chảy nước. Kính hoặc tấm chắn cần vừa, sạch, che được vùng mắt và có khả năng chống UV được ghi rõ khi dùng ngoài trời. Màu tròng đậm không chứng minh khả năng lọc UV. Nếu người chạy xe máy mở kính chắn vì mờ hoặc nóng, cần giải quyết nguyên nhân mờ, thông gió của mũ hoặc chọn thiết bị phù hợp hơn, không coi việc để mắt trần là giải pháp lâu dài. Sau một đoạn đường bụi, rửa tay trước khi chạm mắt hoặc tháo kính áp tròng. Tránh dùng khăn dính bụi chà mạnh lên tròng và mắt. Nếu mắt bị vật bắn rồi đau, đỏ hoặc nhìn mờ, dừng xe và đi khám, không lái tiếp trong tình trạng nhìn không rõ."),
 ("Kính nào phù hợp từng chặng đường?", "Một chuyến giao hàng có thể bắt đầu dưới nắng và kết thúc khi trời tối. Kính râm phù hợp ban ngày không nhất thiết dùng được sau hoàng hôn; chuẩn bị giải pháp chuyển đổi mà không khiến mắt phơi bụi. Kính quang sắc có thể là lựa chọn cho một số người, nhưng mức đổi màu phía sau kính chắn gió và tốc độ đổi theo môi trường cần kiểm tra thực tế. Khi lái ô tô, kính chắn gió và gương cũng tạo phản xạ; điều chỉnh vị trí ghế, tấm che nắng và bề mặt kính sạch trước khi chỉ tăng độ tối của tròng. Với xe máy, thử kính cùng mũ ở tư thế quay đầu và quan sát gương. Người đeo kính cận nên bảo đảm mũ không ép gọng lệch. Nếu công ty cấp thiết bị, nên cho người lái thử nhiều cỡ để có tầm nhìn tốt, thay vì áp một mẫu cho tất cả."),
 ("Làm gì khi mắt cộm trên đường?", "Tấp vào nơi an toàn trước khi kiểm tra mắt. Không vừa lái vừa dụi, tháo kính hay nhỏ thuốc. Rửa tay nếu có điều kiện, rồi xem kính chắn có bụi hoặc vết xước không. Nếu có dị vật nhỏ, có thể làm theo hướng dẫn sơ cứu an toàn tại chỗ; không dùng vật nhọn, que bông hay người khác thổi mạnh vào mắt. Nếu vật cắm, đau nhiều, sợ sáng, đỏ rõ hoặc nhìn mờ, cần được khám sớm. Không tự lái đến cơ sở y tế khi tầm nhìn không bảo đảm; nhờ người hỗ trợ. Ghi lại tình huống: xe chạy qua công trường bụi, vật bắn từ phía trước hay gió mạnh làm mắt khô dần. Những tình huống khác nhau cần biện pháp phòng ngừa khác nhau. Cảm giác đỡ sau vài phút không phải bằng chứng giác mạc chắc chắn không trầy."),
 ("Nghỉ mắt trong lịch chạy liên tục", "Khi liên tiếp nhìn đường, điện thoại định vị và màn hình đơn hàng, mắt phải đổi khoảng cách thường xuyên. Hãy đặt thiết bị định vị ở vị trí có thể liếc nhanh, tránh cúi sát hoặc đọc tin nhắn dài khi đang điều khiển xe. Chỉ xem chi tiết đơn ở điểm dừng an toàn. Trong khoảng nghỉ, có thể nhìn xa, chớp mắt và uống nước theo nhu cầu, thay vì đổi từ một màn hình nhỏ sang màn hình khác liên tục. Nếu mắt khô rát kéo dài, ghi thời gian chạy, điều kiện gió, có dùng kính áp tròng không và triệu chứng có còn khi nghỉ. Điều chỉnh lịch và trang bị có thể giúp, nhưng không thay thế khám nếu nhìn mờ, đau hoặc giảm khả năng quan sát. Một lịch giao hàng an toàn phải cho phép người lái dừng khi tầm nhìn bị ảnh hưởng; ép chạy khi mắt khó nhìn tăng nguy cơ cho nhiều người."),
 ("Kiểm tra thiết bị trước và sau chuyến", "Trước chuyến, lau mặt chắn và kính đúng vật liệu, nhìn ngược sáng để phát hiện xước ở vùng trung tâm, kiểm tra gọng và mũ có chắc không. Thử mở, đóng mặt chắn khi đứng yên và xem có hơi nước đọng bất thường. Chuẩn bị khăn sạch, hộp kính và phương án cho lúc trời tối. Sau chuyến, loại bỏ bụi bám theo hướng dẫn để không chà hạt cứng lên tròng; cất kính tránh bị đè. Nếu một loại mũ liên tục làm gọng lệch hoặc che góc nhìn, báo người phụ trách để đổi cỡ hoặc kiểu. Khi nhiều người chạy cùng tuyến gặp chói hoặc bụi ở cùng đoạn đường, có thể điều chỉnh lịch, lộ trình hoặc trang bị. Bảo dưỡng thiết bị nhìn là việc nhỏ lặp hằng ngày nhưng quan trọng hơn một lần mua kính rồi quên kiểm tra."),
],
}
