"""Long-form, article-specific workplace eye guidance (second group)."""

MORE = {
"mai-khoan-kim-loai-bao-ve-mat": [
 ("Mảnh bắn xuất hiện cả khi không trực tiếp cầm máy", "Trong xưởng, người đứng cạnh máy mài vẫn có thể ở trên đường đi của hạt kim loại, bụi và mảnh vỡ. Việc chỉ phát kính cho người vận hành nhưng để người quan sát đứng sát bên không được che chắn tạo khoảng trống an toàn. Trước ca, cần xác định vùng phát sinh mảnh bắn, hướng máy và vị trí những người khác. Tấm chắn của máy, màn ngăn khu vực và bảo vệ mắt cá nhân giải quyết các phần nguy cơ khác nhau; không nên dùng một biện pháp để bỏ hẳn biện pháp kia. Khi chuyển từ mài sang khoan hoặc cắt, tính chất vật bắn có thể đổi, vì vậy phải xem lại thiết bị phù hợp. Nếu người lao động phải bỏ kính ra để nhìn đường cắt, cần giải quyết độ rõ và độ vừa của kính trước, không coi việc tháo kính là một cách làm việc chấp nhận được. Một lần chưa bị thương không chứng minh vị trí đứng ấy an toàn."),
 ("Chọn bảo hộ theo việc đang làm", "Kính an toàn che mắt và hai bên mặt, kính ôm kín và tấm che mặt có những vai trò khác nhau. Công việc tạo nhiều mảnh nhỏ, bụi hoặc có nguy cơ va đập cần lựa chọn dựa trên đánh giá nguy cơ tại nơi làm việc và hướng dẫn của người phụ trách an toàn. Kính cận thông thường không tự trở thành kính an toàn vì tròng dày. Nếu phải đeo hai lớp, thử khi cúi, quay đầu và nói chuyện để chắc không lớp nào làm lớp kia xô lệch. Với thao tác tạo tia hoặc ánh sáng đặc biệt, yêu cầu bảo vệ có thể khác với mài cơ học; đừng dùng một chiếc kính cho mọi công đoạn chỉ vì tiện. Thiết bị đã nứt, xước nặng hoặc không còn giữ đúng vị trí cần được thay theo quy trình. Người dùng nên được biết vì sao chọn loại đó và cách báo khi thiết bị gây mờ, hơi nước hoặc đau ở sống mũi."),
 ("Kiểm tra khu vực trước khi bật máy", "Dành một phút quan sát hướng mảnh bắn, độ chắc của chi tiết gia công và vị trí đồng nghiệp. Dọn vật cản trên lối đi để không phải vội quay đầu khi máy hoạt động. Kiểm tra kính sạch, tròng không nứt, gọng không lỏng và mắt nhìn rõ dấu thao tác. Nếu dùng kính có độ, bảo đảm kính an toàn lắp đúng và không bóp gọng kính cận vào mặt. Chỗ chiếu sáng quá yếu dễ làm người thợ tiến sát vật; chỗ chiếu sáng phản xạ mạnh lại khiến họ nheo mắt. Trao đổi để chỉnh ánh sáng chung của bàn làm việc, đồng thời giữ che chắn theo quy trình. Khi máy có tấm chắn, đặt đúng vị trí; không nâng lên vì thấy vướng mà chưa có biện pháp thay thế được phê duyệt. Việc quan sát trước máy giúp phòng sự cố, nhưng không thay thế đào tạo vận hành và quy định an toàn cụ thể của xưởng."),
 ("Nếu cảm giác có hạt kim loại trong mắt", "Dừng công việc và tránh dụi mắt. Dụi có thể làm trầy bề mặt nhãn cầu hoặc khiến dị vật di chuyển; tự dùng nhíp, nam châm hay que bông để gắp cũng có thể gây tổn thương thêm. Nếu có mảnh cắm, đau nhiều, chảy nước mắt, sợ sáng hoặc nhìn mờ, cần được đánh giá y tế sớm. Không để một người khác thổi vào mắt hoặc cố dùng khí nén để làm sạch. Nếu đó là bụi rời và nơi làm việc có quy trình rửa mắt, thực hiện theo hướng dẫn an toàn, nhưng đừng vì thấy bớt cộm mà bỏ qua khám khi triệu chứng còn. Nói rõ vật liệu đang gia công, công đoạn, thời điểm xảy ra, có dùng kính hay không và đã xử trí gì. Thông tin này giúp bác sĩ đánh giá nguy cơ dị vật còn sót và người phụ trách sửa quy trình để người khác không gặp sự cố tương tự."),
 ("Sau một sự cố cần xem lại hệ thống bảo vệ", "Thay một chiếc kính vỡ là cần thiết nhưng chưa đủ nếu mảnh bắn vẫn đi qua cùng lối đó. Người quản lý nên xem mảnh đến từ máy đang dùng, máy lân cận hay từ vị trí chi tiết gia công; rồi xem tấm chắn, khoảng cách và hướng đứng có hợp lý không. Nếu tai nạn xảy ra lúc tháo kính do mờ, cần tìm nguyên nhân mờ: hơi thở, độ ẩm, tròng xước, kính không vừa hay công việc đòi nhìn chi tiết quá nhỏ. Nên cho người lao động thử phương án thay thế trước ca tiếp theo. Việc ghi nhận cả sự cố suýt xảy ra giúp nhận diện nơi nguy hiểm trước khi có chấn thương nặng. Người bị thương cần tiếp tục tuân thủ lịch khám và điều trị, không tự quay lại công đoạn tạo mảnh bắn chỉ vì mắt đã hết đỏ trong ngày. Phòng ngừa tốt cần cả thiết bị, tổ chức công việc và thói quen đúng."),
 ("Phân biệt kích ứng với dấu hiệu khẩn", "Cộm nhẹ sau khi ở xưởng có thể do bụi, nhưng cũng có thể do một dị vật nhỏ khó nhìn bằng mắt thường. Đau nhói, sợ ánh sáng, đỏ tăng, chảy nước mắt liên tục hoặc thị lực thay đổi là dấu hiệu không nên theo dõi tại nhà. Nếu mảnh kim loại bay với tốc độ cao, cần nói rõ cơ chế va chạm khi đến cơ sở y tế, kể cả khi bên ngoài mắt không có vết lớn. Không tự nhỏ thuốc tê, thuốc có steroid hoặc đắp lá; giảm đau nhất thời không chứng minh mắt lành. Nếu chỉ một mắt bị, có thể che bảo vệ nhẹ trên đường đi khám nhưng không ấn lên nhãn cầu. Đồng nghiệp cần giúp người bệnh đến nơi khám và giữ thông tin về vật liệu gia công. Cách xử trí sớm là một phần của an toàn lao động, không phải sự bất tiện nên trì hoãn cho đến hết ca."),
],
"nuoc-tay-rua-ban-vao-mat-khi-lam-viec": [
 ("Những phút đầu quan trọng hơn việc tìm tên thuốc nhỏ", "Khi dung dịch tẩy rửa bắn vào mắt, điều cần làm ngay là bắt đầu xối rửa bằng nhiều nước sạch tại trạm rửa mắt hoặc vòi nước phù hợp, đồng thời gọi người hỗ trợ. Không chờ quản lý đến, không đi tìm đơn kính hay thuốc nhỏ trước. Giữ mí mắt mở để nước tiếp xúc các vùng dưới mí, tránh để dòng nước đưa hóa chất sang mắt còn lại. Người đeo kính áp tròng không nên trì hoãn rửa chỉ để tháo kính; trong quá trình rửa, có thể tháo nếu làm được an toàn. Sau đó cần đánh giá y tế, đặc biệt nếu đau, đỏ, nhìn mờ hoặc chưa rõ thành phần dung dịch. Thời gian và cách xối rửa cụ thể phải theo hướng dẫn an toàn của sản phẩm và nhân viên cấp cứu. Một cảm giác bớt rát tạm thời không chứng minh bề mặt mắt đã hết nguy cơ tổn thương."),
 ("Biết mình đang pha và dùng hóa chất nào", "Tên thương mại trên chai lớn và dung dịch đã pha loãng trong bình nhỏ có thể khác nhau. Tại nơi làm việc, mọi bình sử dụng nên có nhãn phù hợp để người lao động biết thành phần, nồng độ và hướng dẫn ứng phó khi xảy ra sự cố. Không đổ chất tẩy từ bao gốc vào chai nước uống vì rất dễ gây nhầm lẫn. Trước khi bắt đầu công việc mới, hãy xác định vị trí bảng dữ liệu an toàn hóa chất, điểm rửa mắt và số liên lạc khẩn; đừng đợi đến lúc mắt đau mới đi tìm. Nếu hóa chất bắn vào mắt, mang theo nhãn hoặc ảnh rõ của sản phẩm khi đi khám, nhưng chỉ sau khi đã bắt đầu rửa. Nói rõ có pha với chất khác hay không, vì tên một sản phẩm riêng lẻ có thể không phản ánh hỗn hợp thực tế. Không tự trung hòa bằng giấm, chanh hoặc một hóa chất khác."),
 ("Bố trí công việc để giảm giọt bắn", "Khi pha dung dịch, đặt bình trên bề mặt chắc, rót chậm và tránh đưa miệng chai ngang tầm mắt. Vòi phun cần được chỉnh đúng hướng; đầu phun tắc không nên thông bằng cách nhìn thẳng vào lỗ phun. Người làm vệ sinh không chỉ đối diện nguy cơ lúc pha mà cả lúc lau bề mặt phía trên đầu, chà nhà vệ sinh và đổ nước bẩn. Hãy xem thao tác nào tạo giọt bắn rồi chọn kính hoặc tấm che theo đánh giá của nơi làm việc. Găng tay cũng quan trọng vì bàn tay dính hóa chất dễ đưa lên dụi mắt. Tránh để kính bảo vệ quá mờ khiến người lao động phải tháo khi đang xử lý hóa chất; thay thiết bị phù hợp và sạch. Khi dùng nhiều sản phẩm, không pha trộn theo kinh nghiệm truyền miệng. Nơi làm việc nên hướng dẫn rõ thứ tự pha và những chất tuyệt đối không dùng chung."),
 ("Hỗ trợ đồng nghiệp đang bị bắn vào mắt", "Người chứng kiến nên dẫn nạn nhân đến nơi rửa mắt, mở lối đi, gọi hỗ trợ và lấy nhãn sản phẩm. Không dùng tay bẩn mở mí mạnh hay cố kiểm tra bằng ánh đèn sát mắt. Nếu hóa chất dính quần áo hoặc găng, xử lý theo quy trình để tránh tiếp tục tiếp xúc. Người đang đau có thể khó tự giữ mắt mở, nên cần hướng dẫn bình tĩnh để dòng nước chảy liên tục. Nếu chỉ một mắt bị, chú ý hướng đầu để nước chảy ra ngoài, giảm nguy cơ sang mắt lành. Ghi thời điểm sự cố và thời điểm bắt đầu rửa; đừng chờ ghi biểu mẫu trước khi sơ cứu. Sau khi chuyển đến cơ sở y tế, nơi làm việc cần xem lại nguyên nhân: bình phun, thao tác pha, không đủ thiết bị bảo hộ, trạm rửa mắt bị chắn hay thiếu đào tạo. Mục tiêu là sửa hệ thống, không chỉ nhắc người bị nạn ‘cẩn thận hơn’."),
 ("Đi khám ngay cả khi đã rửa", "Khám mắt sau phơi nhiễm giúp đánh giá bề mặt giác mạc, kết mạc và mức độ tổn thương mà người bệnh không thể tự nhận định bằng gương. Người bệnh nên nêu loại sản phẩm, dạng lỏng hay bột, có đeo kính áp tròng không, thời gian tiếp xúc và quá trình rửa. Nếu có nhãn hoặc bảng dữ liệu an toàn, đưa cho nhân viên y tế xem; không đưa một chai hóa chất rò rỉ vào phòng khám. Không tự nhỏ thuốc giảm đỏ hoặc đắp thuốc khi chưa có chỉ định, vì một số sản phẩm có thể che triệu chứng hoặc không phù hợp. Cần tuân thủ hẹn tái khám nếu bác sĩ yêu cầu, dù sau vài giờ mắt có vẻ đỡ. Nếu thị lực giảm, đau tăng, mắt trắng đục hoặc khó mở mắt, đây là dấu hiệu cần xử lý khẩn. Với hóa chất không rõ tên, hãy nói thẳng là chưa rõ, không đoán để có một câu trả lời nhanh."),
 ("Chuẩn bị trạm rửa mắt trước khi cần đến", "Một điểm rửa mắt chỉ có giá trị nếu người lao động tìm thấy và dùng được ngay. Hãy kiểm tra lối đi không bị chất hàng che, nguồn nước hoạt động, người làm ca đêm biết vị trí và có phương án khi mất điện hoặc nước. Người mới vào làm nên được thực hành chỉ đường từ vị trí pha hóa chất đến trạm rửa. Biển chỉ dẫn cần dễ nhìn giữa những thiết bị và chai lọ thường ngày. Nếu công việc chuyển sang khu vực khác, kiểm tra lại điểm rửa gần nơi mới. Nhà quản lý có thể diễn tập một tình huống giả định để thấy ai sẽ gọi hỗ trợ và ai lấy thông tin sản phẩm, không cần đợi xảy ra tai nạn thật. Khi điều kiện thực tế không cho phép rửa mắt kịp thời, cần xử lý rủi ro trước khi tiếp tục công việc. Đây là khâu chuẩn bị của cả cơ sở, không nên để từng người tự xoay xở."),
],
}
