"""Further original long-form sections: outdoor, clinical, protective eyewear."""

MORE = {
"lam-viec-ngoai-troi-bao-ve-mat-tia-uv": [
 ("Nắng không chỉ mạnh vào giữa trưa", "Người làm ngoài trời thường chú ý đến ánh sáng chói trước mặt mà bỏ qua ánh sáng phản chiếu từ mặt đường, nước, kính hoặc bề mặt sáng. Tia cực tím vẫn có thể là vấn đề trong những ngày nhiều mây; cảm giác mát hơn không phải phép đo lượng tia mắt nhận được. Người đi giao hàng, làm công trình, làm vườn hoặc giám sát hiện trường có thời gian phơi nắng và hướng nhìn khác nhau. Vì vậy, lựa chọn kính nên dựa vào khả năng chống tia UV được ghi rõ, độ che phủ và mức nhìn rõ khi làm việc, không chỉ dựa vào màu tròng. Kính rất tối nhưng không có thông tin lọc UV có thể tạo cảm giác an toàn sai. Nên kết hợp kính với mũ có vành khi công việc cho phép, tìm bóng râm trong giờ nghỉ, đồng thời tuân thủ quy định bảo hộ khác ở nơi làm việc. Mục tiêu là giảm tiếp xúc kéo dài, không phải làm mọi cảnh vật trở nên tối."),
 ("Đọc nhãn kính như thế nào?", "Tìm thông tin sản phẩm cho biết kính chặn gần như toàn bộ UVA và UVB hoặc UV400, từ nhà bán có thể giải thích nguồn gốc và tiêu chuẩn. Giá cao, tròng tráng gương hoặc màu đậm không tự bảo đảm mức lọc tia. Kính ôm vừa mặt, che được ánh sáng đi từ hai bên sẽ hữu ích hơn loại chỉ che một vùng hẹp phía trước. Người đang dùng kính cận có thể hỏi về tròng cận chống UV, kính chụp ngoài hoặc loại phù hợp nghề nghiệp; đừng hy sinh việc nhìn rõ để dùng một kính râm không đúng độ khi lái xe hoặc vận hành máy. Nếu phải đọc màn hình ngoài trời, kiểm tra kính có làm giảm khả năng phân biệt thông tin quan trọng không. Với công việc có mảnh văng, kính râm thông thường không thay thiết bị bảo vệ mắt được đánh giá theo nguy cơ; có thể cần một giải pháp đáp ứng cả hai yêu cầu."),
 ("Lịch làm việc và môi trường phản chiếu", "Trong một ca làm, hãy xác định những đoạn phải đứng lâu dưới nắng hoặc nhìn về bề mặt phản chiếu. Nếu có thể, chuyển việc hành chính vào chỗ râm và bố trí nghỉ ngắn ở khu vực được che chắn. Người làm gần nước hoặc nền bê tông sáng có thể bị chói từ dưới lên, nên vành mũ đơn thuần không chắn hết ánh sáng; kính che quanh mắt trở nên quan trọng. Khi đeo khẩu trang và mũ bảo hộ, thử kính cùng toàn bộ thiết bị để xem tròng có mờ hơi nước hoặc bị đẩy lệch. Nếu kính bị mờ khi chuyển vào chỗ mát, dừng thao tác cần nhìn chính xác để lau an toàn, thay vì tháo kính ở ngay vùng nguy cơ. Đồng nghiệp có thể giúp đánh giá vị trí làm việc nào chưa có bóng râm hoặc ánh sáng khiến khó nhận diện biển báo. Điều chỉnh điều kiện làm việc là trách nhiệm tổ chức, không chỉ chuyện mua kính của từng người."),
 ("Có cần đeo kính cả khi trời râm?", "Không thể suy từ mây che, màu trời hoặc cảm giác nóng lạnh ra mức tia UV tại chỗ. Khi kế hoạch làm việc là ở ngoài trời lâu, người lao động nên chuẩn bị bảo vệ mắt trước ca và dùng nhất quán theo điều kiện thực tế. Nếu kính khiến nhìn tối trong khu vực thiếu sáng, cần loại phù hợp hoặc thay đổi khi chuyển môi trường; không đeo tròng quá tối khi vận hành phương tiện trong tình huống cần quan sát rõ. Kính quang sắc có thể thay đổi độ đậm theo điều kiện, nhưng hiệu quả khi ngồi sau kính chắn gió và yêu cầu công việc cần được kiểm tra riêng. Người quản lý cần chú ý công việc bắt đầu sớm, kéo dài chiều muộn và những ca luân phiên, vì mỗi ca có góc nắng khác nhau. Cách phù hợp là đánh giá khả năng nhìn rõ, bảo vệ UV và an toàn thao tác cùng lúc."),
 ("Khi nào khó chịu vì nắng cần khám?", "Chói mắt có thể đơn giản là môi trường quá sáng, nhưng đau, đỏ, sợ ánh sáng rõ, nhìn mờ kéo dài hoặc khó chịu chỉ ở một mắt cần được đánh giá. Không tự cho rằng đeo kính râm là đủ nếu khả năng nhìn giảm. Người có tiền sử bệnh mắt, phẫu thuật mắt hoặc đang dùng thuốc có câu hỏi riêng về bảo vệ nắng nên hỏi bác sĩ điều trị. Khi đi khám, kể thời gian ở ngoài trời, loại kính đang đeo, triệu chứng bắt đầu khi nào và còn khi vào trong nhà không. Nếu mắt đỏ đau đột ngột, giảm thị lực hay có chấn thương kèm theo, nên đi khám sớm. Bảo vệ mắt khỏi UV là việc lâu dài; khám mắt giúp xử lý triệu chứng hiện tại và chọn biện pháp phù hợp với thị lực, chứ không phải chỉ để mua một chiếc kính mới."),
 ("Một danh sách chuẩn bị trước ca ngoài trời", "Kiểm tra kính sạch, không trầy vùng nhìn chính, ôm vừa và không tuột khi cúi. Mang theo hộp hoặc khăn lau phù hợp để cất kính khi chuyển vào nơi không cần dùng. Xem vị trí mũ, kính bảo hộ nghề nghiệp và khẩu trang có cản nhau không. Nếu công việc phải lái xe, thử đọc đồng hồ, gương, tín hiệu và biển báo trong điều kiện ánh sáng thay đổi; nếu không rõ, chọn giải pháp khác trước khi đi. Chuẩn bị nước uống, nơi nghỉ và che nắng cho toàn thân theo quy định an toàn lao động, vì bảo vệ mắt là một phần của bảo vệ sức khỏe khi làm ngoài trời. Nếu nhiều người cùng phản ánh nắng chiếu trực diện ở một công đoạn cố định, hãy đề xuất che chắn chung. Đừng đánh giá kết quả bằng việc hôm nay không đau mắt; mục đích là giảm phơi nhiễm tích lũy trong những ngày làm việc lặp lại."),
],
"nhan-vien-y-te-kinh-bao-ve-mat-giot-ban": [
 ("Bảo vệ mắt gắn với từng thủ thuật", "Không phải mọi cuộc trao đổi với người bệnh đều có cùng nguy cơ giọt bắn. Khi dự kiến dịch cơ thể có thể văng, nhân viên cần dùng bảo vệ mắt theo đánh giá nguy cơ và quy trình kiểm soát nhiễm khuẩn của cơ sở. Các tình huống có thể gồm thủ thuật tạo dịch bắn, lấy mẫu, chăm sóc người bệnh ho nhiều hoặc xử lý dụng cụ bẩn. Hãy xác định nguy cơ trước khi mang găng và bắt đầu thủ thuật, vì tìm kính sau khi đã tiếp xúc thường quá muộn. Kính bảo hộ và tấm che mặt cần che đúng vùng, vừa với khẩu trang và các thiết bị khác. Kính cận là thiết bị điều chỉnh thị lực, thường không che kín vùng mắt khỏi giọt bắn. CDC/NIOSH nhấn mạnh lựa chọn bảo vệ mắt phù hợp với nguy cơ phơi nhiễm; nơi làm việc phải có quy trình cụ thể để nhân viên áp dụng thống nhất."),
 ("Đeo và tháo là hai thời điểm khác nhau", "Lúc đeo, kiểm tra tròng rõ, dây hoặc gọng còn chắc, kính không đẩy khẩu trang lệch. Trong thủ thuật, tránh chạm tay dính dịch lên mặt kính để chỉnh liên tục. Khi tháo, phần trước kính có thể đã nhiễm bẩn; chỉ cầm ở vùng được quy trình cho phép và thực hiện vệ sinh tay đúng bước. Không đặt kính vừa dùng lên bàn sạch hoặc treo vào cổ áo rồi mang về. Thiết bị tái sử dụng cần làm sạch, khử khuẩn và bảo quản theo chính sách của cơ sở và hướng dẫn nhà sản xuất; thiết bị dùng một lần cần xử lý đúng loại. Các bước cụ thể có thể thay đổi theo thủ thuật, loại thiết bị và chính sách kiểm soát nhiễm khuẩn, nên nhân viên không tự thay bằng mẹo cá nhân. Diễn tập thao tác tháo ở nơi ít áp lực giúp giảm sai sót khi đang bận."),
 ("Kính bị mờ trong lúc khám hoặc thủ thuật", "Hơi thở thoát lên trên khẩu trang, độ ẩm phòng và kính không vừa đều có thể làm tròng mờ. Nếu không nhìn rõ, hãy dừng thao tác ở điểm an toàn, điều chỉnh theo quy trình và thay thiết bị nếu cần. Không lật kính lên trán trong khi đang ở vùng nguy cơ, vì vùng trán không phải nơi cất thiết bị đã có thể dính giọt bắn. Kiểm tra độ kín của khẩu trang và vị trí gọng trước khi thủ thuật bắt đầu; sản phẩm chống mờ chỉ dùng khi phù hợp với vật liệu kính và chính sách cơ sở. Mỗi loại gương mặt có thể cần kích cỡ hoặc kiểu khác nhau. Một bộ kính đặt đúng chỗ nhưng buộc người dùng nhìn qua lớp sương liên tục không bảo đảm an toàn cho cả nhân viên lẫn người bệnh. Phản ánh tình trạng mờ với bộ phận kiểm soát nhiễm khuẩn để sửa lựa chọn thiết bị, không tự bỏ kính."),
 ("Sau phơi nhiễm cần làm gì?", "Nếu giọt dịch bắn vào mắt, hãy thực hiện sơ cứu và báo cáo theo quy trình phơi nhiễm nghề nghiệp của cơ sở ngay, không chờ hết ca. Thông tin cần ghi gồm thủ thuật đang làm, loại dịch, thời điểm, mắt nào bị, thiết bị đang đeo và bước sơ cứu đã thực hiện. Bộ phận y tế nghề nghiệp hoặc kiểm soát nhiễm khuẩn sẽ hướng dẫn đánh giá tiếp theo tùy nguồn phơi nhiễm; nhân viên không tự suy đoán rủi ro từ vẻ ngoài người bệnh. Nếu mắt có đau, đỏ hoặc nhìn mờ, cần được khám mắt bên cạnh đánh giá phơi nhiễm. Không dùng chung thuốc nhỏ hoặc dung dịch không được quy định để xử trí. Một hệ thống báo cáo không đổ lỗi giúp tìm xem kính không có sẵn, không vừa hay quy trình thao tác đã tạo giọt bắn ngoài dự kiến, từ đó ngăn sự cố lặp lại."),
 ("Khác biệt giữa kính bảo hộ và tấm che mặt", "Tấm che mặt bảo vệ một vùng rộng trên mặt và có thể hữu ích khi giọt bắn nhiều, nhưng cấu tạo mở ở phía dưới hoặc hai bên có thể để giọt đi vào. Kính bảo hộ phù hợp có thể che sát mắt hơn; lựa chọn dùng riêng hay phối hợp cần dựa trên đánh giá rủi ro và hướng dẫn cơ sở. Không quyết định chỉ theo cảm giác dễ chịu hoặc hình ảnh quảng cáo. Kiểm tra tấm che có làm méo hình, cản góc nhìn hoặc va vào dụng cụ không. Nếu người làm đeo kính cận, cần thử toàn bộ tổ hợp để bảo đảm không lớp nào bị đẩy lệch. Chỗ cất sạch và nguồn cung đủ cỡ giúp nhân viên dùng đúng hơn việc chỉ phát một kiểu duy nhất. Khi đổi từ phòng khám sang khu xử lý dụng cụ, nguy cơ thay đổi; thiết bị cũng phải được xem lại, không mang một tấm che bẩn qua nhiều khu vực."),
 ("Đào tạo nên dựa trên ca làm thật", "Hãy chọn vài tình huống quen thuộc của khoa: bệnh nhân ho khi khám gần mặt, rửa dụng cụ, lấy mẫu hoặc hỗ trợ thủ thuật. Với mỗi tình huống, nhân viên xác định giọt bắn có thể đi đâu, chọn thiết bị, thử đeo và diễn tập tháo. Người phụ trách quan sát những điểm thiết bị bị mờ hoặc xô lệch, rồi sửa lựa chọn hoặc thao tác. Một bảng hướng dẫn treo ở nơi nhận thiết bị hữu ích hơn bản quy định dài ít người đọc trong ca trực. Nhân viên mới và nhân viên luân chuyển khoa cần được hướng dẫn tại chỗ, vì nguy cơ không giống nhau giữa các vị trí. Nên kiểm tra kính tái sử dụng được làm sạch ra sao, ai chịu trách nhiệm và có đủ thời gian giữa hai ca. Mục tiêu là duy trì tầm nhìn rõ, bảo vệ mắt và kiểm soát nhiễm khuẩn cùng lúc."),
],
"kinh-bao-ho-bi-mo-hoac-tray": [
 ("Mờ hơi nước và trầy xước không xử lý giống nhau", "Hơi nước thường thay đổi theo độ ẩm, hơi thở, nhiệt độ và vị trí khẩu trang; vết trầy tồn tại cố định khi kính đã khô. Hãy đứng ở vùng an toàn, lau kính bằng vật liệu phù hợp rồi nhìn qua một đoạn chữ hoặc chi tiết nhỏ dưới ánh sáng làm việc. Nếu vệt mờ biến mất sau khi chỉnh luồng hơi, cần cải thiện độ vừa hoặc lựa chọn kiểu kính. Nếu vẫn có vệt cố định, tròng có thể đã trầy hoặc lớp phủ hỏng, nên đánh giá thay thế. Không dùng giấy nhám, kem đánh răng hoặc dung môi không được khuyến nghị để ‘đánh bóng’ vì có thể làm biến dạng tròng và giảm khả năng bảo vệ. Một chiếc kính mờ cản nhận diện vật nguy hiểm, còn việc tháo kính trong vùng nguy cơ làm mất hẳn bảo vệ. Cả hai đều là vấn đề an toàn cần báo người phụ trách."),
 ("Kiểm tra độ vừa khi mang nhiều thiết bị", "Kính có thể vừa khi đứng một mình nhưng lệch khi mang khẩu trang, mũ bảo hộ hoặc kính cận. Hãy thử toàn bộ thiết bị như trong ca làm thật: cúi, quay đầu, đọc nhãn và thực hiện động tác mô phỏng. Nếu dây đeo quá chặt gây đau hoặc quá lỏng làm kính trượt, cần chỉnh đúng giới hạn nhà sản xuất hoặc đổi cỡ. Khẩu trang có hơi thở thoát lên tròng cần được đeo đúng cách; không kéo khẩu trang xuống dưới mũi để giảm mờ. Người làm trong kho lạnh có thể gặp sương khi chuyển qua hai vùng nhiệt độ; chuẩn bị thời gian để kính thích nghi và phương án lau an toàn. Không bôi hóa chất lên tròng khi chưa biết tương thích. Một giải pháp tốt phải giữ cả khả năng nhìn và mức che chắn, thay vì cải thiện mặt này bằng cách bỏ mặt kia."),
 ("Khi nào nên thay kính?", "Tròng nứt, lỏng, xước sâu ở vùng nhìn, gọng biến dạng hoặc dây không giữ được vị trí là những lý do cần thay theo quy trình. Nếu kính từng chịu va đập mạnh, người phụ trách nên xem hướng dẫn nhà sản xuất và đánh giá lại, dù chưa thấy vỡ. Lớp phủ chống mờ bong hoặc tròng đục có thể làm người dùng phải nghiêng đầu để tìm góc nhìn rõ, đặc biệt nguy hiểm khi dùng máy. Đừng chờ đến khi kính không thể nhìn xuyên qua mới báo; ghi nhận sớm giúp có kính dự phòng trước ca. Một chiếc kính mới cũng không tự phù hợp nếu sai cỡ hoặc sai loại nguy cơ. Người lao động cần được biết cách yêu cầu đổi thiết bị và thời gian nhận thiết bị thay thế, để không phải chọn giữa làm việc không nhìn rõ và làm việc không bảo hộ."),
 ("Vệ sinh kính đúng cách", "Bụi khô có thể làm trầy tròng nếu dùng áo hoặc giấy thô chà mạnh. Làm sạch theo hướng dẫn của nhà sản xuất, chú ý nước, chất tẩy và khăn được phép dùng cho lớp phủ. Kính dùng chung tại cơ sở y tế hoặc nơi có nguy cơ nhiễm bẩn còn cần quy trình khử khuẩn tương ứng; không thể chỉ lau bằng khăn cá nhân. Cất kính trong hộp hoặc chỗ sạch, tránh mặt tròng cọ vào kim loại và tránh nhiệt độ gây biến dạng. Khi người dùng nhận kính đầu ca, nên kiểm tra tầm nhìn dưới ánh sáng thực tế, không chỉ nhìn qua kính ở kho dụng cụ. Nếu kính liên tục bẩn sau vài phút làm việc, xem lại nguồn bụi hoặc giọt bắn tại công đoạn, vì vệ sinh thường xuyên không giải quyết nguyên nhân. Hỏi người dùng khó nhìn ở bước nào sẽ giúp phân biệt bẩn, mờ và thiết kế không phù hợp."),
 ("Một cuộc trao đổi an toàn nên có gì?", "Người lao động có thể báo ‘kính này không nhìn được vạch đo’ thay vì chỉ nói ‘kính khó chịu’. Người phụ trách cần hỏi vạch ở khoảng cách nào, dưới ánh sáng nào, kính mờ lúc bắt đầu hay sau vài phút và có mang thiết bị nào khác. Thử kính dự phòng trong một đoạn công việc an toàn, kiểm tra dấu chất lượng và mức che chắn rồi ghi phương án được chấp thuận. Nếu nhiều người gặp cùng lỗi, nên xem cả lô kính, cách bảo quản hoặc thiết kế nơi làm việc. Không phạt việc báo kính hỏng bằng cách buộc người lao động dùng lại kính đó. Thông tin về lúc xảy ra vấn đề giúp người mua thiết bị chọn đúng hơn cho lần sau. Đây là vòng phản hồi quan trọng giữa người dùng thực tế và người quản lý an toàn, nhất là khi công việc thay đổi theo mùa hoặc thiết bị mới."),
 ("Phân biệt khó nhìn do kính với khó nhìn do mắt", "Nếu tháo kính bảo hộ ở vùng an toàn mà chữ vẫn mờ, hoặc nhìn kém cả ngoài công việc, cần xem xét thị lực thay vì chỉ thay tròng bảo hộ. Người có kính cận mới, kính áp tròng hoặc thay đổi thị lực có thể cần giải pháp bảo hộ phù hợp với độ nhìn. Ngược lại, nếu chỉ một chiếc kính cụ thể làm méo hình, hãy kiểm tra thiết bị trước. Không tự lái xe hoặc vận hành máy khi tầm nhìn không rõ để ‘quen dần’. Người bị đau mắt, đỏ mắt, nhìn đôi hoặc giảm thị lực đột ngột cần được khám theo mức độ khẩn, không chờ đợt phát kính mới. Việc hỏi cả điều kiện nhìn bên ngoài xưởng giúp tránh nhầm giữa lỗi thiết bị và vấn đề sức khỏe. Hai khả năng có thể cùng tồn tại, vì thế cần xử lý thiết bị đồng thời khuyến khích người lao động được kiểm tra mắt khi có triệu chứng."),
],
}
