"""Article-specific guidance for construction and agricultural chemical exposure."""

MORE = {
"bui-xi-mang-vao-mat-cong-truong": [
 ("Vì sao xi măng khác bụi đường thông thường?", "Xi măng khô có thể bay thành hạt nhỏ khi đổ bao, trộn vật liệu, quét sàn hoặc tháo cốp pha. Khi gặp ẩm, vật liệu có tính kiềm và có thể gây tổn thương mắt; vì vậy cảm giác cộm sau khi bị bột xi măng bắn không nên coi là chuyện nhỏ. Không thể nhìn ngoài mắt để biết còn hạt ở dưới mí hay mức độ bề mặt mắt đã bị ảnh hưởng. Người lao động thường dụi mắt vì tưởng chỉ là bụi, nhưng hành động này có thể làm trầy thêm. Hãy báo ngay cho người phụ trách, rời vùng bụi và dùng điểm rửa mắt theo quy trình an toàn của công trường. Nếu có đau, đỏ, chảy nước mắt, sợ ánh sáng hoặc nhìn mờ, cần được nhân viên y tế đánh giá kịp thời. Kể cả sau khi bớt cộm, việc ghi rõ loại vật liệu và cách tiếp xúc vẫn giúp bác sĩ xem xét nguy cơ phù hợp."),
 ("Những thời điểm dễ bị bụi bắn", "Nguy cơ không chỉ xuất hiện lúc trực tiếp trộn vữa. Người xé bao xi măng, đổ vật liệu từ trên cao, dùng máy khuấy, chà bề mặt khô hoặc đứng gần xe đổ nguyên liệu đều có thể gặp bụi. Gió đổi hướng làm đám bụi đi về phía người quan sát. Trước ca, nhóm nên thống nhất ai làm công đoạn tạo bụi, khu vực cách ly, hướng gió và vị trí rửa mắt. Giảm bụi tại nguồn bằng thao tác, che chắn hoặc kỹ thuật được công trường phê duyệt, đồng thời dùng bảo vệ mắt phù hợp. Khẩu trang che đường hô hấp không thay cho kính bảo vệ mắt; kính cận thông thường cũng để hở. Khi công việc trên cao, cần chú ý bụi rơi xuống mặt người bên dưới. Một quy trình rõ cho cả người làm chính và người đi ngang hiệu quả hơn lời nhắc chung chung rằng ‘đừng đứng gần’."),
 ("Rửa mắt và chuyển đi khám", "Nếu bột hoặc vữa vào mắt, tránh dụi. Bắt đầu xối rửa với nước sạch ngay theo hướng dẫn tại nơi làm việc; giữ mí mở để nước cuốn vật liệu ra ngoài. Không cố dùng khăn khô cọ vào bề mặt mắt, không nhỏ dầu hoặc các dung dịch tự pha để trung hòa. Nếu đang đeo kính áp tròng, không trì hoãn xối rửa chỉ để tìm cách tháo kính. Sau sơ cứu, cần được khám, nhất là khi mắt đau, đỏ, khó mở hoặc nhìn giảm. Khi đi khám, nói rõ xi măng khô hay vữa ướt, lượng ước tính, mắt nào bị, đã rửa trong bao lâu và còn cộm không. Trường hợp có vật cắm vào mắt hoặc bị lực va mạnh cần xử trí khác với bụi rời; không tự lấy vật đó ra. Sự an toàn của người bệnh quan trọng hơn việc hoàn thành ca trộn đang dang dở."),
 ("Chọn kính mà vẫn làm việc được", "Kính quá rộng có thể để bụi đi vào từ cạnh; kính quá kín nhưng liên tục mờ có thể khiến người lao động tháo ra. Người phụ trách an toàn cần chọn loại phù hợp nguy cơ bụi và mảnh bắn, cho thử cùng mũ, khẩu trang và thiết bị khác. Kiểm tra kính khi cúi xách bao, ngửa nhìn vật liệu và xoay đầu; đây là những tư thế thực tế hơn việc thử đứng yên. Tròng xước hoặc phủ bột làm tầm nhìn kém, cần được vệ sinh hoặc thay theo hướng dẫn. Nếu công trường đổi công đoạn từ trộn thủ công sang cắt vật liệu, có thể xuất hiện nguy cơ mảnh văng khác; đánh giá lại bảo hộ trước khi làm. Nên đặt kính sạch ở vị trí dễ lấy cho người vào khu vực ngắn, không để khách hoặc thợ phụ nghĩ rằng họ ‘chỉ đứng nhìn’ nên không cần bảo vệ."),
 ("Trao đổi sau tai nạn để tránh lặp lại", "Khi một người bị bụi xi măng vào mắt, nên ghi nhận công đoạn, hướng gió, thiết bị bảo hộ đang đeo và điểm rửa mắt có hoạt động không. Hỏi liệu bao bị rách, đổ từ quá cao, có người đi ngang vùng trộn hay không; tránh chỉ quy lỗi cho người bị nạn. Nếu không có điểm rửa dễ đến, cần sửa ngay. Nếu nhiều người phản ánh kính bị mờ hoặc không vừa, hãy đánh giá lại loại kính, cách bảo quản và cỡ cho từng người. Người đã được khám cần theo dõi theo chỉ dẫn bác sĩ trước khi quay lại môi trường bụi. Khi thị lực hoặc mức độ đau thay đổi, phải tái khám thay vì tự dùng thuốc cũ. Những bài học từ một sự cố nhỏ có thể phòng một chấn thương nặng hơn ở công đoạn tiếp theo."),
 ("Người giám sát nên chuẩn bị gì?", "Danh sách kiểm tra trước ca có thể rất ngắn: nơi tạo bụi, che chắn tại nguồn, kính cho người làm và người ở gần, điểm rửa mắt, số liên lạc và lối ra khỏi vùng thi công. Người mới cần biết báo cho ai khi có bụi vào mắt. Ca làm ngoài trời cần xem hướng gió thay đổi, còn khu vực kín cần xem bụi đọng trên bề mặt và khả năng thông gió. Không dùng khí nén thổi bụi khỏi mặt người vì có thể đẩy hạt vào mắt mạnh hơn. Dụng cụ vệ sinh nên phù hợp quy trình công trường để tránh tạo thêm đám bụi khi quét khô. Nếu có nhà thầu phụ, cùng thống nhất vùng nguy cơ; tai nạn không phân biệt nhân sự thuộc nhóm nào. Việc chuẩn bị này không thay thế quy định pháp luật hoặc đánh giá chuyên môn an toàn lao động tại từng cơ sở, nhưng giúp biến quy định thành thao tác cụ thể."),
],
"phun-thuoc-bao-ve-thuc-vat-bao-ve-mat": [
 ("Đọc nhãn trước khi pha và phun", "Thuốc bảo vệ thực vật không phải một chất duy nhất: mỗi sản phẩm có hoạt chất, dạng pha, mức nguy cơ và hướng dẫn sơ cứu riêng. Trước khi mở nắp, người sử dụng cần đọc nhãn, xác định thiết bị bảo vệ mắt được yêu cầu và vị trí nước sạch để rửa nếu xảy ra sự cố. Không chuyển thuốc sang chai đồ uống hoặc bình không nhãn. Nếu người lao động không đọc rõ chữ nhỏ trên nhãn, hãy tìm cách phóng to hoặc nhờ người được đào tạo đọc cùng trước khi pha; không ước lượng bằng trí nhớ. Hướng gió, đầu vòi phun và áp lực phun ảnh hưởng nơi giọt bắn đến. Quy trình an toàn địa phương và hướng dẫn sản phẩm cần được ưu tiên hơn mẹo truyền miệng. Người tham gia công việc dù chỉ đi cùng để hỗ trợ cũng nên được biết cách tránh vùng phun và cách giúp khi có giọt vào mắt."),
 ("Rủi ro ở khâu pha có thể khác khâu phun", "Khi pha, dung dịch có thể ở nồng độ cao hơn lúc sử dụng ngoài đồng. Việc mở nắp, đong, rót và thông đầu phun là những lúc giọt có thể bắn gần mặt. Trước thao tác, đặt bình trên nền vững, dùng dụng cụ đong theo hướng dẫn và giữ mặt xa miệng bình. Không dùng miệng để thông ống phun. Khi phun, chú ý gió đổi hướng và người ở rìa khu vực; tránh phun khi điều kiện thời tiết không phù hợp theo nhãn. Không nâng kính lên trán để lau mồ hôi bằng găng có thuốc; tay hoặc găng nhiễm hóa chất có thể làm thuốc đi thẳng vào mắt. Sau công việc, tháo thiết bị theo quy trình để không chạm phần bẩn vào mặt. Bảo vệ mắt phải đi cùng bảo vệ da và đường hô hấp theo đánh giá nguy cơ, không dùng một món thay cho các món còn lại."),
 ("Khi thuốc bắn vào mắt", "Hãy bắt đầu xối rửa mắt bằng nước sạch ngay và làm theo hướng dẫn sơ cứu trên nhãn sản phẩm hoặc cơ quan cấp cứu. Giữ mắt mở, tránh làm dòng nước chảy từ mắt bị nhiễm sang mắt còn lại. Đừng chờ cảm giác rát tăng mới rửa, cũng đừng nhỏ dầu, sữa hay chất khác để ‘trung hòa’. Nếu mang kính áp tròng, không trì hoãn rửa để tìm hộp đựng; xử lý kính khi có thể làm an toàn trong quá trình rửa. Gọi người hỗ trợ và liên hệ y tế; mang nhãn hoặc ảnh sản phẩm để nhân viên y tế biết chính xác chất đã tiếp xúc. Nếu không biết loại thuốc, nói rõ là chưa biết. Mắt bớt cay không có nghĩa là có thể tiếp tục phun ngay, vì mức độ tổn thương không thể đánh giá đủ chỉ bằng cảm giác. Người lao động cần được kiểm tra và hướng dẫn cụ thể trước khi quay lại công việc."),
 ("Thông tin cần mang khi đến cơ sở y tế", "Tên thương mại, hoạt chất ghi trên nhãn, dạng bột hay lỏng, thuốc đã pha hay còn đậm đặc, thời gian bắn vào mắt, thời điểm bắt đầu rửa và mắt nào bị đều là thông tin hữu ích. Nếu có triệu chứng toàn thân như buồn nôn, chóng mặt, khó thở hoặc da dính thuốc, cũng phải thông báo vì tiếp xúc có thể không chỉ ở mắt. Không tự đoán liều hóa chất nếu không rõ; mô tả lượng bắn bằng hoàn cảnh thực tế. Có thể chụp cả mặt trước lẫn hướng dẫn sơ cứu của bao bì, nhưng không để việc chụp ảnh trì hoãn rửa mắt. Người đi cùng nên mang thông tin sản phẩm và giúp ghi nhớ diễn biến, để người bệnh tập trung được chăm sóc. Các triệu chứng xuất hiện sau khi về nhà hoặc tăng lên cần được báo lại cho cơ sở y tế theo hướng dẫn. Không dùng kinh nghiệm của lần tiếp xúc với một loại thuốc khác để xử trí lần này."),
 ("Bảo quản và quản lý dụng cụ", "Thuốc nên ở nguyên bao bì hoặc vật chứa được phép, có nhãn đọc được và cất ngoài tầm với của người không được giao nhiệm vụ. Bình phun hỏng, vòi rò hoặc dây nối lỏng cần được sửa trước khi sử dụng; dùng tạm có thể tạo tia thuốc hướng về mặt. Kính bảo vệ mắt cần sạch, vừa và được bảo quản riêng khỏi phần thiết bị dính thuốc. Sau ca, xử lý nước rửa, quần áo và thiết bị theo quy định an toàn của sản phẩm và địa phương; không mang găng hoặc khăn bẩn dùng lau mắt vào khu sinh hoạt. Nên có người biết quy trình ứng phó khi người phun làm một mình ở nơi xa: ai gọi giúp, nước sạch ở đâu, đường đến cơ sở y tế thế nào. Lập kế hoạch này đặc biệt quan trọng khi phải làm ngoài đồng, nơi việc tìm trạm rửa và liên lạc có thể khó hơn trong nhà."),
 ("Nhìn lại quy trình sau lần bị bắn", "Sự cố có thể đến từ mở nắp bị kẹt, bình quá đầy, hướng gió đổi, trượt chân hoặc kính không khít. Ghi lại tình huống để cải thiện đúng bước, thay vì chỉ nhắc người phun chú ý hơn. Nếu người lao động nói kính mờ, nóng hoặc không vừa, hãy tìm thiết bị đạt yêu cầu nhưng dùng được trong điều kiện thực tế. Tổ chức hướng dẫn ngắn cho cả người pha, người phun, người dọn thiết bị và người hỗ trợ; mỗi người có thời điểm tiếp xúc khác nhau. Kiểm tra nhãn sản phẩm được dùng hiện tại, vì thay thuốc có thể thay luôn yêu cầu bảo vệ. Sau khám, tuân thủ khuyến nghị điều trị và hẹn tái khám; không đưa người vừa bị sự cố trở lại vùng phun khi còn nhìn mờ. Phòng ngừa tốt là một chuỗi: đọc nhãn, kiểm soát thao tác, dùng thiết bị, có nước rửa và biết đường tìm trợ giúp."),
],
}
