"""Further article-specific sections. This is editorial copy, never automatic padding."""

MORE = {
"man-hinh-bi-loa-khi-lam-viec": [
 ("Khác nhau giữa phản chiếu và chữ khó đọc", "Một vùng trắng hoặc hình cửa sổ xuất hiện trên mặt kính là phản chiếu; chữ nhỏ, nét mảnh hoặc độ tương phản thấp lại là vấn đề hiển thị. Hai điều này có thể cùng xảy ra nhưng cần thử riêng. Mở cùng một trang ở hai vị trí trong phòng, không thay cỡ chữ: nếu chỉ chỗ ngồi cạnh cửa sổ khó nhìn, hãy ưu tiên xử lý ánh sáng. Sau đó giữ nguyên vị trí và tăng cỡ chữ, đổi chế độ hiển thị của ứng dụng để xem mắt có bớt phải nheo không. Người dùng thường tăng độ sáng màn hình để thắng phản chiếu, nhưng cách này có thể tạo chênh lệch lớn với giấy in xung quanh. Cũng đừng hạ độ sáng đến mức mọi dòng chữ đều mờ. Mục tiêu là nhìn được cả nội dung số và tài liệu giấy mà không phải liên tục thay tư thế. Việc ghi nhận phép thử này giúp trao đổi cụ thể với bộ phận kỹ thuật hoặc bác sĩ."),
 ("Nếu chỉ một người trong phòng thấy lóa", "Không nên kết luận người đó quá nhạy cảm hoặc chắc chắn có bệnh mắt. Vị trí ghế, chiều cao người ngồi, loại kính đang đeo và nhiệm vụ đọc có thể khác đồng nghiệp. Hãy hỏi họ nhìn thấy vệt sáng ở đâu, vào giờ nào, trên màn hình hay trên bề mặt kính; sau đó đứng đúng vị trí của họ để kiểm tra. Nếu đang đeo kính, lau sạch tròng và nhìn thử qua phần giữa tròng, tránh nhầm vệt bẩn trên kính với lóa từ màn hình. Khi một mắt khó chịu rõ hơn, hoặc mắt mờ cả ngoài nơi làm việc, cần khuyến khích khám mắt thay vì chỉ đổi chỗ ngồi. Cách tiếp cận này tách vấn đề cá nhân khỏi điều kiện môi trường, đồng thời tránh bỏ qua dấu hiệu cần được đánh giá. Mỗi thay đổi nên đủ nhỏ để còn biết nó có tác dụng hay không."),
 ("Những điều nên kể trong buổi khám", "Bác sĩ sẽ có thêm dữ kiện nếu người bệnh mô tả khoảng cách nhìn, số giờ làm việc và điều kiện ánh sáng thay vì chỉ nói ‘mỏi mắt’. Có thể ghi thời điểm xuất hiện lóa, màn hình nào gây khó chịu, có kèm khô rát, nhức đầu, nhìn đôi hay không. Mang kính đang dùng, đơn kính cũ nếu còn, và cho biết công việc phải chuyển mắt giữa giấy và màn hình thường xuyên đến đâu. Nếu đã thay ánh sáng trong một tuần, kể cả thay đổi không có ích. Những dữ kiện này không tự xác định được chẩn đoán nhưng giúp bác sĩ cân nhắc khám khúc xạ, bề mặt nhãn cầu hoặc vấn đề khác phù hợp. Không cần tự mua tròng lọc màu hay kính ‘chống lóa’ theo quảng cáo trước khi biết nhu cầu cụ thể. Nếu mất thị lực đột ngột, đau nhiều hoặc đỏ dữ dội, hãy đi khám sớm, không đợi đến lịch định kỳ."),
],
"vi-tri-man-hinh-va-goc-nhin": [
 ("Chỉnh đồng thời ghế, bàn và thiết bị", "Đặt màn hình đúng mà ghế quá thấp vẫn có thể khiến người dùng ngửa cổ; ghế vừa chiều cao nhưng bàn phím ở quá xa lại khiến vai căng và người cúi về phía trước. Hãy bắt đầu bằng tư thế ngồi vững, bàn chân có điểm tựa và vai thư giãn. Sau đó đưa bàn phím vào vị trí dễ thao tác, mới chỉnh màn hình đến vùng nhìn thẳng. Người dùng máy tính xách tay có thể kê thiết bị để màn hình dễ nhìn nhưng khi ấy bàn phím gắn liền sẽ cao; bàn phím rời là một lựa chọn khi công việc kéo dài. Với máy tính để bàn, giá đỡ màn hình không cần đắt: điều quan trọng là chắc chắn, không rung và cho phép chỉnh lại khi cần. Đừng coi một ảnh bàn làm việc trên mạng là chuẩn cho tất cả mọi người, vì chiều cao, tầm nhìn và nhiệm vụ rất khác nhau."),
 ("Đừng để cuộc họp trực tuyến phá tư thế", "Khi họp, người dùng có thể chú ý đến khuôn mặt trên màn hình nhỏ ở góc và cúi sát trong nhiều chục phút. Hãy phóng lớn cửa sổ họp hoặc đưa người đang nói về vùng nhìn chính. Nếu đồng thời ghi chép, đặt tài liệu gần màn hình để mắt không phải liên tục chuyển giữa hai khoảng cách rất khác. Máy quay đặt quá thấp có thể khiến người dùng ngửa hoặc cúi đầu để ‘trông đẹp’ trên hình; điều chỉnh máy quay riêng nếu được. Một cuộc họp dài không nhất thiết buộc nhìn chằm chằm liên tục; khi không phải đọc chi tiết, có thể nhìn xa trong những khoảng ngắn. Nếu mắt mỏi chủ yếu ở họp, ghi điều này khi đánh giá chỗ làm. Nếu khó nhìn rõ người và chữ cả trong cuộc sống hằng ngày, hãy khám thị lực, không quy tất cả cho phần mềm họp."),
 ("Bàn làm việc dùng chung cần quy ước dễ chỉnh", "Ở nơi nhiều người dùng chung máy, vị trí màn hình hợp với ca trước có thể không hợp ca sau. Nên cho phép chỉnh chiều cao ghế, độ nghiêng màn hình, độ phóng đại chữ và ánh sáng mà không làm hỏng cấu hình chung. Một nhãn nhỏ đánh dấu mức đã thử có thể giúp mỗi người khôi phục nhanh khi bắt đầu ca. Nếu thiết bị cố định, hãy ưu tiên những thay đổi an toàn như ghế điều chỉnh được, khoảng cách giữa mắt và màn hình, cỡ chữ; tránh chồng vật không chắc chắn dưới chân đế. Khi người lao động liên tục phải cúi sát, đừng coi đó là thói quen xấu; có thể họ không đọc rõ do cỡ chữ, kính không phù hợp hoặc độ tương phản kém. Người quản lý nên hỏi cụ thể nhiệm vụ nào gây khó chịu và hỗ trợ sửa điều kiện làm việc trước khi yêu cầu họ cố chịu."),
],
"kho-mat-trong-phong-dieu-hoa": [
 ("Một ngày làm việc có thể có nhiều tác nhân cùng lúc", "Không khí lạnh, luồng gió trực tiếp, nhìn màn hình lâu và ít chớp mắt có thể xuất hiện cùng lúc, nên không thể chỉ từ cảm giác cay mà kết luận máy điều hòa là nguyên nhân duy nhất. Hãy quan sát mắt vào ngày nghỉ và ngày làm việc, ở chỗ ngồi cũ và khi chuyển vị trí, trong cuộc họp không dùng màn hình và khi nhập liệu liên tục. Nếu triệu chứng thay đổi rõ theo vị trí, xem miệng gió có thổi vào mặt không. Nếu đi kèm nhiều giờ nhìn gần, điều chỉnh thời gian nghỉ và chớp mắt có chủ ý cũng đáng thử. Người đeo kính áp tròng cần để ý thời gian đeo và cách chăm sóc kính. Những ghi chép này giúp tìm yếu tố có thể sửa được, nhưng không thay thế khám khi khô kéo dài hoặc có đau, đỏ, nhìn mờ."),
 ("Nước mắt nhân tạo không phải lúc nào cũng giống nhau", "Nhiều người tự mua bất kỳ lọ nhỏ mắt nào có chữ ‘giảm đỏ’ để xử lý khô rát. Các sản phẩm nhỏ mắt có thành phần và mục đích khác nhau; một lọ làm mắt bớt đỏ tạm thời không nhất thiết xử lý nguyên nhân gây khô. Không dùng chung lọ với đồng nghiệp, không để đầu lọ chạm mắt và đọc hạn dùng sau mở nắp. Nếu thường phải nhỏ nhiều lần, đang đeo kính áp tròng hoặc có bệnh mắt khác, hãy hỏi nhân viên y tế sản phẩm phù hợp thay vì kéo dài việc tự dùng. Cũng không nên thay toàn bộ biện pháp môi trường bằng thuốc nhỏ: luồng gió vẫn thổi vào mặt và màn hình vẫn ở góc khó nhìn thì khó chịu có thể tái diễn. Khi mắt đỏ đau, sợ ánh sáng hoặc giảm thị lực, việc tự thử hết loại này sang loại khác có thể làm chậm chẩn đoán."),
 ("Theo dõi triệu chứng theo nơi và giờ", "Một bảng ghi chép đơn giản có thể gồm giờ bắt đầu ca, chỗ ngồi, có đeo kính áp tròng không, khi nào mắt khô nhất, mắt nào nặng hơn và nhìn có mờ không. Không cần ghi điểm số phức tạp. Hãy thử đổi một yếu tố trong vài ngày, chẳng hạn chỉnh hướng gió, rồi so với những ngày tương tự. Nếu chỉ giảm vài phút sau khi nhỏ mắt nhưng tái phát suốt ca, nên mang thông tin đó khi khám. Bác sĩ có thể cần hỏi về thuốc đang dùng, bệnh toàn thân và thói quen chăm sóc mắt; đừng tự suy ra nguyên nhân từ một đoạn quảng cáo. Nếu môi trường quá khô cho nhiều người, hãy trao đổi với bộ phận phụ trách cơ sở vật chất để xem điều kiện phòng chung. Tự mang máy tạo ẩm đặt sát thiết bị điện chưa chắc là giải pháp phù hợp cho nơi làm việc."),
],
"kinh-ap-trong-khi-lam-viec-nhieu-bui": [
 ("Kính áp tròng có phải là thiết bị bảo hộ?", "Kính áp tròng chỉ điều chỉnh thị lực, không có chức năng chắn mảnh bắn, bụi hay hóa chất cho toàn bộ mắt. Người đeo kính vẫn phải dùng thiết bị bảo vệ mắt đúng nguy cơ công việc và đúng yêu cầu nơi làm việc. Khi chọn kính bảo hộ, cần thử độ vừa với mặt và kính đang dùng để không hình thành khe hở lớn. Không nên dựa vào cảm giác ‘đã có một lớp kính trên mắt’ để bỏ kính bảo hộ. Với môi trường có nguy cơ hóa chất, người phụ trách an toàn cần đánh giá công việc, thiết bị và quy trình ứng phó trước; việc được phép đeo kính áp tròng hay không phụ thuộc đánh giá này. NIOSH không xem việc đeo kính áp tròng là lý do tự động cấm người lao động làm việc với hóa chất, nhưng cũng nhấn mạnh phải có bảo vệ mắt thích hợp. Quy định tại từng nơi và loại hóa chất cụ thể vẫn cần được tuân thủ."),
 ("Tay bẩn khiến việc tháo kính trở nên khó khăn", "Người làm trong nhà xưởng có thể muốn tháo kính khi mắt cộm, nhưng tay vừa chạm bụi, dầu hoặc bề mặt chung không nên tiếp xúc trực tiếp với mắt. Hãy rời vùng nguy cơ, rửa tay đúng cách và dùng gương, hộp kính, dung dịch được khuyến nghị nếu cần tháo. Không dùng nước máy để ngâm hoặc rửa kính áp tròng theo thói quen. Nếu vật lạ cắm vào mắt, không tự gắp; nếu hóa chất bắn vào mắt, ưu tiên xối rửa khẩn cấp theo hướng dẫn an toàn và đi khám, không cố tìm hộp kính trước. Sự cố ở ca làm đêm càng cần quy trình rõ: điểm rửa mắt ở đâu, ai hỗ trợ, cơ sở nào tiếp nhận. Không đặt toàn bộ trách nhiệm xử lý lên người lao động đang đau và nhìn khó."),
 ("Chuẩn bị cho ca làm nhiều bụi", "Trước ca, kiểm tra kính áp tròng còn trong thời hạn sử dụng và mắt không đỏ, đau, tiết ghèn. Mang theo kính gọng dự phòng nếu có thể, vì phải tháo kính giữa ca sẽ làm việc tiếp khó khăn khi không nhìn rõ. Kiểm tra thiết bị bảo hộ sạch, vừa và không cấn lên kính. Nếu công việc liên tục làm bụi bay vào dưới kính bảo hộ, báo lại để đánh giá loại che chắn khác; đừng chấp nhận hiện tượng này như bình thường. Sau ca, tháo và chăm sóc kính bằng tay sạch theo đúng hướng dẫn sản phẩm, không để bụi từ găng hoặc áo quần dính vào hộp kính. Nếu cộm không hết sau khi tháo, hoặc có đau, sợ sáng, nhìn mờ, đi khám vì giác mạc cần được kiểm tra. Không tự dùng thuốc nhỏ có kháng sinh hay steroid theo lời truyền miệng."),
],
"kinh-can-co-thay-kinh-bao-ho-duoc-khong": [
 ("Đánh giá nguy cơ trước khi chọn kiểu kính", "Khu vực có mảnh văng khác khu vực chỉ có bụi nhẹ, và công việc pha hóa chất lại khác công việc lắp ráp. Vì thế, câu hỏi đầu tiên không phải ‘kính nào đẹp’ mà là mắt có thể bị vật gì tác động, từ hướng nào và ở thời điểm nào. Hãy đọc quy trình an toàn của vị trí làm việc và hỏi người phụ trách loại thiết bị đã được đánh giá phù hợp. Kính cận thường có thể giúp nhìn rõ nhưng không mặc nhiên đạt tiêu chuẩn chống va đập hay che được hai bên mắt. Một chiếc kính bảo hộ đeo ngoài kính cận phải vừa, không ép gọng làm trượt hoặc tạo khe hở. Một số nơi có kính bảo hộ có độ theo đơn; cần được lắp đúng yêu cầu bảo hộ, không chỉ đổi tròng kính thường vào một gọng trông chắc. Không tự suy ra chứng nhận từ màu tròng, độ dày nhìn bằng mắt hay lời quảng cáo."),
 ("Tại sao bảo vệ bên hông lại quan trọng?", "Mảnh nhỏ từ công việc của người bên cạnh hoặc từ bề mặt bật lại có thể đi vào mắt theo hướng người lao động không nhìn thấy trước. Kính cận phổ thông thường để hở quanh mắt, đặc biệt ở hai bên và phía dưới. Khi thử kính bảo hộ, hãy cúi, xoay đầu và thực hiện cử động thường gặp để xem kính có trượt không. Người đeo khẩu trang hoặc tấm che mặt nên kiểm tra các thiết bị có xung đột khiến kính không còn áp sát. Tấm che mặt có thể bảo vệ một vùng rộng hơn nhưng không phải lúc nào cũng thay thế kính bảo hộ bên dưới; lựa chọn phụ thuộc nguy cơ đã đánh giá. Nếu kính mờ đến mức phải tháo ra mới làm được, đó là dấu hiệu cần điều chỉnh hoặc thay loại phù hợp, không phải lý do bỏ bảo hộ. Nhìn rõ cũng là một phần của an toàn công việc."),
 ("Kiểm tra kính sau mỗi ca", "Trước khi vào khu vực nguy cơ, quan sát tròng có xước sâu, nứt, đục hoặc lỏng khỏi gọng không; nhìn qua kính ở ánh sáng làm việc để chắc rằng chi tiết nhỏ vẫn rõ. Sau ca, làm sạch theo hướng dẫn của nhà sản xuất, cất ở chỗ không bị vật nặng đè và không dùng dung môi tùy tiện. Nếu kính từng chịu một cú va mạnh, cần báo người phụ trách để xem có phải thay, dù bề ngoài chưa vỡ. Kính bảo hộ không nên trở thành vật dùng chung mà không được vệ sinh đúng cách và kiểm tra độ vừa cho từng người. Với người có thay đổi độ kính hoặc mới nhận nhiệm vụ khác, cần đánh giá lại cả thị lực lẫn kiểu bảo hộ. Nếu sau sự cố có đau, đỏ, cộm dai dẳng hay nhìn mờ, việc đổi kính cho ca sau không giải quyết tổn thương hiện tại; hãy đi khám."),
],
}
